# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Generic sind-node image — all Slurm roles in a single image.
#
# This is a unified container image based on Rocky Linux 10 that ships every
# Slurm daemon (slurmctld, slurmdbd, slurmd) plus supporting services (munge,
# MariaDB, sshd). sind enables the appropriate services once every node of a
# cluster is up, based on the node's configured role:
#
#   controller — munge, sshd, slurmctld
#   worker     — munge, sshd, slurmd
#   submitter  — munge, sshd
#   db         — munge, sshd, mariadb, slurmdbd
#   api        — munge, sshd, slurmrestd (Slurm 26.05 and later)
#
# The image uses systemd as PID 1 and requires Docker Engine 28+ with
# writable cgroups (no --privileged needed):
#
#   docker run -d \
#       --security-opt writable-cgroups=true \
#       --cgroupns=private \
#       --tmpfs /tmp --tmpfs /run \
#       ghcr.io/gsi-hpc/sind-node:latest
#
# sind starts node containers with its own /bin/sh entrypoint, which enables
# the cgroup controllers for systemd's units and then execs /sbin/init.
#
# Volumes:
#   /etc/slurm  — Slurm configuration (generated by sind)
#   /etc/munge  — shared munge key
#   /data       — user-facing shared data directory
#
# Build (one image per Slurm release line in docker-bake.hcl):
#   docker buildx bake

# ==============================================================================
# Stage: builder-base — Rocky 10 with common build toolchain
# ==============================================================================
# Each builder stage installs into /install, which is all that leaves it, and
# deletes its build tree in the same RUN, so the layer in the build cache
# holds only the installed files.
FROM quay.io/rockylinux/rockylinux:10 AS builder-base

# EPEL and CRB are enabled in the same RUN that ends with dnf clean all, so
# no layer keeps the repository metadata.
RUN dnf -y install epel-release dnf-plugins-core && \
    dnf config-manager --set-enabled crb && \
    dnf -y install \
        gcc gcc-c++ make \
        libevent-devel \
        hwloc-devel \
        python3 perl flex pkgconf \
        tar bzip2 diffutils \
    && dnf clean all

# ==============================================================================
# Stage: ucx-builder — compile UCX from source
# ==============================================================================
FROM builder-base AS ucx-builder

ARG UCX_VERSION=1.20.0

ADD --checksum=sha256:7c8a6093cada179aa1d851b83625e3b25ed5658966e309de5118c27a038c7ef9 \
    https://github.com/openucx/ucx/releases/download/v${UCX_VERSION}/ucx-${UCX_VERSION}.tar.gz \
    /tmp/ucx.tar.gz

WORKDIR /tmp
RUN tar xf ucx.tar.gz && \
    cd ucx-${UCX_VERSION} && \
    ./configure \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        --disable-static \
        --without-cuda \
        --without-rocm \
        --without-java && \
    make -j$(nproc) && \
    DESTDIR=/install make install && \
    cd /tmp && rm -rf ucx-${UCX_VERSION}

# ==============================================================================
# Stage: pmix-builder — compile PMIx from source
# ==============================================================================
FROM builder-base AS pmix-builder

ARG PMIX_VERSION=6.1.0

ADD --checksum=sha256:bb9021c8e100a376f5070ecca727f83a29b5f652dfe381793b88daa79a3b98a2 \
    https://github.com/openpmix/openpmix/releases/download/v${PMIX_VERSION}/pmix-${PMIX_VERSION}.tar.bz2 \
    /tmp/pmix.tar.bz2

WORKDIR /tmp
RUN tar xf pmix.tar.bz2 && \
    cd pmix-${PMIX_VERSION} && \
    ./configure \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        --disable-static && \
    make -j$(nproc) && \
    DESTDIR=/install make install && \
    cd /tmp && rm -rf pmix-${PMIX_VERSION}

# ==============================================================================
# Stage: prrte-builder — compile PRRTE from source (with PMIx 6.x)
# ==============================================================================
FROM builder-base AS prrte-builder

ARG PRRTE_VERSION=4.1.0

COPY --from=pmix-builder /install/usr /usr

ADD --checksum=sha256:285ad62b670075708b9fcfe14c54baa599733bc274d10502a82e8eebba0b7c70 \
    https://github.com/openpmix/prrte/releases/download/v${PRRTE_VERSION}/prrte-${PRRTE_VERSION}.tar.bz2 \
    /tmp/prrte.tar.bz2

WORKDIR /tmp
RUN tar xf prrte.tar.bz2 && \
    cd prrte-${PRRTE_VERSION} && \
    ./configure \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        --disable-static && \
    make -j$(nproc) && \
    DESTDIR=/install make install && \
    cd /tmp && rm -rf prrte-${PRRTE_VERSION}

# ==============================================================================
# Stage: libjwt-builder — compile libjwt 1.x from source
# ==============================================================================
# Slurm's auth/slurm plugin (and with it cred/slurm and sackd's purpose) is
# only built with libjwt, through its 1.x API. libjwt publishes no release
# tarball for 1.18, so the tag is cloned and pinned by its commit.
FROM builder-base AS libjwt-builder

ARG LIBJWT_VERSION=1.18.4
ARG LIBJWT_COMMIT=972802a4d4a0f22d2e171c2eb132de6048a3d951

RUN dnf -y install \
        git \
        autoconf \
        automake \
        libtool \
        pkgconf-m4 \
        jansson-devel \
        openssl-devel \
    && dnf clean all

WORKDIR /tmp
RUN git clone --depth 1 --branch v${LIBJWT_VERSION} https://github.com/benmcollins/libjwt.git libjwt && \
    cd libjwt && \
    test "$(git rev-parse HEAD)" = "${LIBJWT_COMMIT}" && \
    autoreconf -fi && \
    ./configure \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        --disable-static \
        --without-examples && \
    make -j$(nproc) && \
    DESTDIR=/install make install && \
    cd /tmp && rm -rf libjwt

# ==============================================================================
# Stage: slurm-builder — compile Slurm from source (with PMIx support)
# ==============================================================================
FROM builder-base AS slurm-builder

# Every RUN after an ARG sees it, so a new value invalidates its cache. The
# packages come first, so they survive Slurm, PMIx and libjwt bumps and
# install while PMIx and libjwt build.
# llhttp (CRB) is the HTTP parser slurmrestd needs. Slurm 26.05 builds
# slurmrestd with it; 25.11 only knows the archived nodejs http-parser,
# which Rocky 10 does not package, so its images have no slurmrestd.
RUN dnf -y install \
        jansson-devel \
        openssl-devel \
        json-c-devel \
        llhttp-devel \
        munge-devel \
        pam-devel \
        readline-devel \
        perl-ExtUtils-MakeMaker \
        mariadb-devel \
        dbus-devel \
        libbpf-devel \
    && dnf clean all

# PMIx headers and libraries are needed for Slurm's PMIx launch plugin, and
# libjwt's for auth/slurm. auth/slurm also needs the serializer/json plugin,
# which Slurm builds only with json-c.
COPY --from=pmix-builder /install/usr /usr
COPY --from=libjwt-builder /install/usr /usr

# Slurm version and the sha256 of its tarball. No defaults: docker-bake.hcl
# sets both for each image (SLURM_RELEASES).
ARG SLURM_VERSION
ARG SLURM_SHA256

# Fetch the Slurm source tarball with integrity verification.
ADD --checksum=sha256:${SLURM_SHA256} \
    https://download.schedmd.com/slurm/slurm-${SLURM_VERSION}.tar.bz2 /tmp/slurm.tar.bz2

# Configure and install Slurm into a staging root so only the built
# artifacts are copied into the final image (no compiler toolchain).
# make install skips contribs/, so nss_slurm, the NSS module that serves
# the job's user and groups from slurmstepd, is built and installed on its
# own. Its libnss_slurm.so.2 lands in --libdir, /usr/lib64, where glibc
# looks for NSS modules.
#
# Like Slurm's RPM spec, the image ships no static archives and no libtool
# .la files. The debug sections are stripped from every ELF file except
# srun, whose debugger symbols (MPIR) parallel debuggers read.
WORKDIR /tmp
RUN tar xf slurm.tar.bz2 && \
    cd slurm-${SLURM_VERSION} && \
    ./configure \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        --sysconfdir=/etc/slurm \
        --localstatedir=/var \
        --runstatedir=/run \
        --disable-static \
        --with-munge \
        --with-pmix \
        --with-jwt \
        --with-json \
        --with-pam_dir=/usr/lib64/security \
        --with-systemdsystemunitdir=/usr/lib/systemd/system && \
    make -j$(nproc) && \
    make -j$(nproc) -C contribs/nss_slurm && \
    DESTDIR=/install make install && \
    DESTDIR=/install make -C contribs/nss_slurm install && \
    find /install -name '*.la' -delete && \
    find /install -type f ! -name srun \
        -exec sh -c 'test "$(head -c 4 "$1" | tail -c 3)" = ELF' sh {} \; \
        -exec strip --strip-debug {} + && \
    mkdir -p /install/etc && \
    cd /tmp && rm -rf slurm-${SLURM_VERSION}

# ==============================================================================
# Stage: ompi-builder — compile OpenMPI from source (with PRRTE + PMIx + UCX)
# ==============================================================================
FROM builder-base AS ompi-builder

ARG OMPI_VERSION=5.0.10

COPY --from=ucx-builder /install/usr /usr
COPY --from=pmix-builder /install/usr /usr
COPY --from=prrte-builder /install/usr /usr

ADD --checksum=sha256:0acecc4fc218e5debdbcb8a41d182c6b0f1d29393015ed763b2a91d5d7374cc6 \
    https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-${OMPI_VERSION}.tar.bz2 \
    /tmp/openmpi.tar.bz2

WORKDIR /tmp
RUN tar xf openmpi.tar.bz2 && \
    cd openmpi-${OMPI_VERSION} && \
    ./configure \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        --disable-static \
        --with-pmix \
        --with-prrte=external \
        --with-ucx \
        --with-hwloc=external \
        --with-libevent=external \
        --without-cuda \
        --without-rocm && \
    make -j$(nproc) && \
    DESTDIR=/install make install && \
    cd /tmp && rm -rf openmpi-${OMPI_VERSION}

# ==============================================================================
# Stage: runtime — lean image with only the packages needed at run time
# ==============================================================================
# The setup that does not depend on the builds comes first and the version
# ARGs come last, right before the LABEL that uses them: every RUN after an
# ARG sees it, so a new Slurm version would otherwise rebuild the package
# layer too. The images of all release lines and Slurm versions then share
# the layers up to the builder COPYs, and the Slurm layers come last.
FROM quay.io/rockylinux/rockylinux:10 AS runtime

# Runtime dependencies, installed in the RUN that enables EPEL and CRB and
# ends with dnf clean all, so no layer keeps the repository metadata.
# Rocky retags its base image only at minor releases, so the RUN first
# upgrades the base image's packages (glibc, openssl, ...). Building the
# runtime stage without the cache (--no-cache-filter runtime) picks up the
# current errata.
# gcc is needed by mpicc (OpenMPI's wrapper compiler).
# mariadb-server is included for the db role (slurmdbd accounting storage).
# libevent and hwloc-libs are required by PMIx, PRRTE, and OpenMPI at runtime,
# jansson by libjwt, json-c by Slurm's serializer/json, llhttp by slurmrestd.
RUN dnf -y install epel-release dnf-plugins-core && \
    dnf config-manager --set-enabled crb && \
    dnf -y upgrade && \
    dnf -y install \
        systemd \
        munge \
        mariadb-server \
        readline \
        pam \
        procps-ng \
        iproute \
        hostname \
        openssh-server \
        openssh-clients \
        dbus-libs \
        libevent \
        hwloc-libs \
        jansson \
        json-c \
        llhttp \
        gcc \
    && dnf clean all

# Slurm daemons run as the unprivileged slurm user. slurmrestd refuses to
# run as root or SlurmUser, and its unit runs it as slurmrestd. slurm is
# created first, so that its uid stays the same as in older images.
RUN useradd -r -s /sbin/nologin slurm && \
    useradd -r -M -s /sbin/nologin slurmrestd

# State directories for slurmctld and slurmd, plus the shared /data volume
RUN mkdir -p \
        /var/log/slurm \
        /var/spool/slurmctld \
        /var/spool/slurmd \
        /data && \
    chown -R slurm:slurm \
        /var/log/slurm \
        /var/spool/slurmctld \
        /var/spool/slurmd

# Munge requires strict ownership and permissions on its directories
RUN mkdir -p /etc/munge /var/lib/munge /var/log/munge /run/munge && \
    chown -R munge:munge /etc/munge /var/lib/munge /var/log/munge /run/munge && \
    chmod 700 /etc/munge /var/lib/munge /var/log/munge /run/munge

# Allow root login via pubkey only (sind injects authorized_keys at
# container start for inter-node SSH). The image ships no SSH host keys:
# sshd-keygen@.service, which sshd.service pulls in, generates them on each
# container's first boot, before sshd starts, so no two nodes share a key.
# sind pins only the ed25519 key, so sshd serves only that one and the RSA
# and ECDSA key generation is masked.
RUN rm -f /etc/ssh/ssh_host_* && \
    echo 'HostKey /etc/ssh/ssh_host_ed25519_key' > /etc/ssh/sshd_config.d/40-sind-hostkey.conf && \
    systemctl mask sshd-keygen@rsa.service sshd-keygen@ecdsa.service && \
    mkdir -p /run/sshd && \
    sed -i 's/#PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config && \
    sed -i 's/#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config && \
    mkdir -p /root/.ssh && chmod 700 /root/.ssh

# Let root read the shadow files as their owner. Rocky ships them with mode
# 0000, so reading them needs CAP_DAC_OVERRIDE. On nodes with
# apparmor=unconfined, the host's unix-chkpwd AppArmor profile (e.g. on
# Ubuntu 24.04) attaches to unix_chkpwd and denies that capability. pam_unix's
# account check then fails and sshd refuses root logins.
RUN chmod 0400 /etc/shadow /etc/gshadow

# Only munge and sshd are enabled unconditionally — Slurm services
# (slurmctld, slurmdbd, slurmd, slurmrestd) and MariaDB are enabled by sind
# once the cluster's nodes are up, depending on the node's role.
RUN systemctl enable munge sshd

# Mask units that are unnecessary or problematic inside a container.
# Note: sys-fs-fuse-connections.mount is NOT masked — it is a no-op without
# /dev/fuse and must remain unmasked for FUSE to work when containers are
# granted SYS_ADMIN + /dev/fuse via capAdd/devices.
RUN systemctl mask \
    dev-hugepages.mount \
    getty.target \
    console-getty.service

# Cap the journal, which the Slurm daemons log to. journald's defaults let a
# volatile journal in /run, a tmpfs charged to the node's memory limit, grow
# to 10% of /run (half the host's memory), and a persistent one to 4 GB.
RUN mkdir -p /etc/systemd/journald.conf.d && \
    printf '[Journal]\nRuntimeMaxUse=32M\nSystemMaxUse=64M\n' > /etc/systemd/journald.conf.d/50-sind.conf

# Initialise MariaDB's data directory with the script mariadb.service runs
# before its first start, which then finds it initialised: a db node's first
# start then skips mariadb-install-db and the script's one-second sleep.
RUN /usr/libexec/mariadb-prepare-db-dir mysql mysql && \
    test -d /var/lib/mysql/mysql

# Bring in compiled artifacts from each builder stage, Slurm last.
COPY --from=ucx-builder /install/usr /usr
COPY --from=pmix-builder /install/usr /usr
COPY --from=prrte-builder /install/usr /usr
COPY --from=ompi-builder /install/usr /usr
COPY --from=libjwt-builder /install/usr /usr
COPY --from=slurm-builder /install/usr /usr
COPY --from=slurm-builder /install/etc /etc

# Register the new libraries, and fail the build without nss_slurm, the
# auth/slurm plugin and the serializer/json plugin it needs, or sackd, which
# sind's identity modes nssSlurm and clientIds use, or, from Slurm 26.05 on,
# without slurmrestd and its JWT plugin, which sind's api node runs.
RUN ldconfig && \
    test -e /usr/lib64/libnss_slurm.so.2 && \
    test -e /usr/lib64/slurm/auth_slurm.so && \
    test -e /usr/lib64/slurm/serializer_json.so && \
    test -x /usr/sbin/sackd && \
    case "$(slurmctld -V)" in \
        "slurm 25."*) ;; \
        *) test -x /usr/sbin/slurmrestd && \
           test -e /usr/lib64/slurm/rest_auth_jwt.so && \
           test -e /usr/lib64/slurm/http_parser_llhttp_parser.so && \
           test -e /usr/lib/systemd/system/slurmrestd.service ;; \
    esac

ARG SLURM_VERSION
ARG UCX_VERSION=1.20.0
ARG PMIX_VERSION=6.1.0
ARG PRRTE_VERSION=4.1.0
ARG OMPI_VERSION=5.0.10
ARG LIBJWT_VERSION=1.18.4

LABEL org.opencontainers.image.title="sind-node" \
      org.opencontainers.image.description="Generic Slurm node for sind" \
      org.opencontainers.image.version="${SLURM_VERSION}" \
      sind.slurm.version="${SLURM_VERSION}" \
      sind.ucx.version="${UCX_VERSION}" \
      sind.pmix.version="${PMIX_VERSION}" \
      sind.prrte.version="${PRRTE_VERSION}" \
      sind.ompi.version="${OMPI_VERSION}" \
      sind.libjwt.version="${LIBJWT_VERSION}"

VOLUME ["/etc/slurm", "/etc/munge", "/data"]
WORKDIR /data

# systemd expects SIGRTMIN+3 for a clean container shutdown
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
