# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Generic sind-node image — all Slurm roles in a single image.
#
# This is a unified container image based on Rocky Linux 10 that ships every
# Slurm daemon (slurmctld, slurmdbd, slurmd) plus supporting services (munge,
# MariaDB, sshd). sind enables the appropriate services at container start
# based on the node's configured role:
#
#   controller — munge, sshd, slurmctld
#   db         — munge, sshd, mariadb, slurmdbd
#   compute    — munge, sshd, slurmd
#   submitter  — munge, sshd
#
# The image uses systemd as PID 1 and requires Docker Engine 28+ with
# writable cgroups (no --privileged needed):
#
#   docker run -d \
#       --security-opt writable-cgroups=true \
#       --cgroupns=private \
#       --tmpfs /tmp --tmpfs /run \
#       ghcr.io/gsi-hpc/sind-node:latest
#
# Volumes:
#   /etc/slurm  — Slurm configuration (generated by sind)
#   /etc/munge  — shared munge key
#   /data       — user-facing shared data directory
#
# Build:
#   docker buildx bake

# ==============================================================================
# Stage: builder-base — Rocky 10 with common build toolchain
# ==============================================================================
FROM quay.io/rockylinux/rockylinux:10 AS builder-base

RUN dnf -y install epel-release dnf-plugins-core && \
    dnf config-manager --set-enabled crb

RUN dnf -y install \
        gcc gcc-c++ make \
        libevent-devel \
        hwloc-devel \
        python3 perl flex pkgconf \
        tar bzip2 diffutils \
    && dnf clean all

# ==============================================================================
# Stage: ucx-builder — compile UCX from source
# ==============================================================================
FROM builder-base AS ucx-builder

ARG UCX_VERSION=1.20.0

ADD --checksum=sha256:7c8a6093cada179aa1d851b83625e3b25ed5658966e309de5118c27a038c7ef9 \
    https://github.com/openucx/ucx/releases/download/v${UCX_VERSION}/ucx-${UCX_VERSION}.tar.gz \
    /tmp/ucx.tar.gz

WORKDIR /tmp
RUN tar xf ucx.tar.gz && \
    cd ucx-${UCX_VERSION} && \
    ./configure \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        --disable-static \
        --without-cuda \
        --without-rocm \
        --without-java && \
    make -j$(nproc) && \
    DESTDIR=/install make install

# ==============================================================================
# Stage: pmix-builder — compile PMIx from source
# ==============================================================================
FROM builder-base AS pmix-builder

ARG PMIX_VERSION=6.1.0

ADD --checksum=sha256:bb9021c8e100a376f5070ecca727f83a29b5f652dfe381793b88daa79a3b98a2 \
    https://github.com/openpmix/openpmix/releases/download/v${PMIX_VERSION}/pmix-${PMIX_VERSION}.tar.bz2 \
    /tmp/pmix.tar.bz2

WORKDIR /tmp
RUN tar xf pmix.tar.bz2 && \
    cd pmix-${PMIX_VERSION} && \
    ./configure \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        --disable-static && \
    make -j$(nproc) && \
    DESTDIR=/install make install

# ==============================================================================
# Stage: prrte-builder — compile PRRTE from source (with PMIx 6.x)
# ==============================================================================
FROM builder-base AS prrte-builder

ARG PRRTE_VERSION=4.1.0

COPY --from=pmix-builder /install/usr /usr

ADD --checksum=sha256:285ad62b670075708b9fcfe14c54baa599733bc274d10502a82e8eebba0b7c70 \
    https://github.com/openpmix/prrte/releases/download/v${PRRTE_VERSION}/prrte-${PRRTE_VERSION}.tar.bz2 \
    /tmp/prrte.tar.bz2

WORKDIR /tmp
RUN tar xf prrte.tar.bz2 && \
    cd prrte-${PRRTE_VERSION} && \
    ./configure \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        --disable-static && \
    make -j$(nproc) && \
    DESTDIR=/install make install

# ==============================================================================
# Stage: slurm-builder — compile Slurm from source (with PMIx support)
# ==============================================================================
FROM builder-base AS slurm-builder

ARG SLURM_VERSION=25.11.4

# PMIx headers and libraries are needed for Slurm's PMIx launch plugin.
COPY --from=pmix-builder /install/usr /usr

RUN dnf -y install \
        munge-devel \
        pam-devel \
        readline-devel \
        perl-ExtUtils-MakeMaker \
        mariadb-devel \
        dbus-devel \
        libbpf-devel \
    && dnf clean all

# Fetch the Slurm source tarball with integrity verification.
# The checksum must be updated when SLURM_VERSION changes.
ADD --checksum=sha256:237f515adcb37b99ff6cb3e1fa81691a5f7188e94c3b6b495858b4eaecf6531d \
    https://download.schedmd.com/slurm/slurm-${SLURM_VERSION}.tar.bz2 /tmp/slurm.tar.bz2

# Configure and install Slurm into a staging root so only the built
# artifacts are copied into the final image (no compiler toolchain).
WORKDIR /tmp
RUN tar xf slurm.tar.bz2 && \
    cd slurm-${SLURM_VERSION} && \
    ./configure \
        --prefix=/usr \
        --sysconfdir=/etc/slurm \
        --localstatedir=/var \
        --runstatedir=/run \
        --with-munge \
        --with-pmix \
        --with-pam_dir=/usr/lib64/security \
        --with-systemdsystemunitdir=/usr/lib/systemd/system && \
    make -j$(nproc) && \
    DESTDIR=/install make install && \
    mkdir -p /install/etc

# ==============================================================================
# Stage: ompi-builder — compile OpenMPI from source (with PRRTE + PMIx + UCX)
# ==============================================================================
FROM builder-base AS ompi-builder

ARG OMPI_VERSION=5.0.10

COPY --from=ucx-builder /install/usr /usr
COPY --from=pmix-builder /install/usr /usr
COPY --from=prrte-builder /install/usr /usr

ADD --checksum=sha256:0acecc4fc218e5debdbcb8a41d182c6b0f1d29393015ed763b2a91d5d7374cc6 \
    https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-${OMPI_VERSION}.tar.bz2 \
    /tmp/openmpi.tar.bz2

WORKDIR /tmp
RUN tar xf openmpi.tar.bz2 && \
    cd openmpi-${OMPI_VERSION} && \
    ./configure \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        --disable-static \
        --with-pmix \
        --with-prrte=external \
        --with-ucx \
        --with-hwloc=external \
        --with-libevent=external \
        --without-cuda \
        --without-rocm && \
    make -j$(nproc) && \
    DESTDIR=/install make install

# ==============================================================================
# Stage: runtime — lean image with only the packages needed at run time
# ==============================================================================
FROM quay.io/rockylinux/rockylinux:10

ARG SLURM_VERSION=25.11.4
ARG UCX_VERSION=1.20.0
ARG PMIX_VERSION=6.1.0
ARG PRRTE_VERSION=4.1.0
ARG OMPI_VERSION=5.0.10

RUN dnf -y install epel-release dnf-plugins-core && \
    dnf config-manager --set-enabled crb

# Runtime dependencies.
# gcc is needed by mpicc (OpenMPI's wrapper compiler).
# mariadb-server is included for the db role (slurmdbd accounting storage).
# libevent and hwloc-libs are required by PMIx, PRRTE, and OpenMPI at runtime.
RUN dnf -y install \
        systemd \
        munge \
        mariadb-server \
        readline \
        pam \
        procps-ng \
        iproute \
        hostname \
        openssh-server \
        openssh-clients \
        dbus-libs \
        libevent \
        hwloc-libs \
        gcc \
    && dnf clean all

# Bring in compiled artifacts from each builder stage.
COPY --from=slurm-builder /install/usr /usr
COPY --from=slurm-builder /install/etc /etc
COPY --from=ucx-builder /install/usr /usr
COPY --from=pmix-builder /install/usr /usr
COPY --from=prrte-builder /install/usr /usr
COPY --from=ompi-builder /install/usr /usr

# Slurm daemons run as the unprivileged slurm user
RUN useradd -r -s /sbin/nologin slurm

# State directories for slurmctld and slurmd, plus the shared /data volume
RUN mkdir -p \
        /var/log/slurm \
        /var/spool/slurmctld \
        /var/spool/slurmd \
        /data && \
    chown -R slurm:slurm \
        /var/log/slurm \
        /var/spool/slurmctld \
        /var/spool/slurmd

# Munge requires strict ownership and permissions on its directories
RUN mkdir -p /etc/munge /var/lib/munge /var/log/munge /run/munge && \
    chown -R munge:munge /etc/munge /var/lib/munge /var/log/munge /run/munge && \
    chmod 700 /etc/munge /var/lib/munge /var/log/munge /run/munge

# Pre-generate SSH host keys and allow root login via pubkey only
# (sind injects authorized_keys at container start for inter-node SSH)
RUN ssh-keygen -A && \
    mkdir -p /run/sshd && \
    sed -i 's/#PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config && \
    sed -i 's/#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config && \
    mkdir -p /root/.ssh && chmod 700 /root/.ssh

# Only munge and sshd are enabled unconditionally — Slurm services
# (slurmctld, slurmdbd, slurmd) are enabled by sind at container start
# depending on the node's role.
RUN systemctl enable munge sshd

# Mask units that are unnecessary or problematic inside a container.
# Note: sys-fs-fuse-connections.mount is NOT masked — it is a no-op without
# /dev/fuse and must remain unmasked for FUSE to work when containers are
# granted SYS_ADMIN + /dev/fuse via capAdd/devices.
RUN systemctl mask \
    dev-hugepages.mount \
    getty.target \
    console-getty.service

LABEL org.opencontainers.image.title="sind-node" \
      org.opencontainers.image.description="Generic Slurm node for sind" \
      org.opencontainers.image.version="${SLURM_VERSION}" \
      sind.slurm.version="${SLURM_VERSION}" \
      sind.ucx.version="${UCX_VERSION}" \
      sind.pmix.version="${PMIX_VERSION}" \
      sind.prrte.version="${PRRTE_VERSION}" \
      sind.ompi.version="${OMPI_VERSION}"

VOLUME ["/etc/slurm", "/etc/munge", "/data"]
WORKDIR /data

# systemd expects SIGRTMIN+3 for a clean container shutdown
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
