# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Generic sind-node image — all Slurm roles in a single image.
#
# This is a unified container image based on Rocky Linux 10 that ships every
# Slurm daemon (slurmctld, slurmdbd, slurmd) plus supporting services (munge,
# MariaDB, sshd). sind enables the appropriate services at container start
# based on the node's configured role:
#
#   controller — munge, sshd, slurmctld
#   db         — munge, sshd, mariadb, slurmdbd
#   compute    — munge, sshd, slurmd
#   submitter  — munge, sshd
#
# The image uses systemd as PID 1 and requires Docker Engine 28+ with
# writable cgroups (no --privileged needed):
#
#   docker run -d \
#       --security-opt writable-cgroups=true \
#       --cgroupns=private \
#       --tmpfs /tmp --tmpfs /run \
#       ghcr.io/gsi-hpc/sind-node:latest
#
# Volumes:
#   /etc/slurm  — Slurm configuration (generated by sind)
#   /etc/munge  — shared munge key
#   /data       — user-facing shared data directory
#
# Build:
#   docker buildx bake

# ==============================================================================
# Stage 1: Builder — compile Slurm from source
# ==============================================================================
FROM quay.io/rockylinux/rockylinux:10 AS builder

ARG SLURM_VERSION=25.11.4

# EPEL + CRB are required for munge-devel and other build headers
RUN dnf -y install epel-release dnf-plugins-core && \
    dnf config-manager --set-enabled crb

# Build toolchain and Slurm's compile-time dependencies
RUN dnf -y install \
        gcc gcc-c++ make \
        munge-devel \
        pam-devel \
        readline-devel \
        perl-ExtUtils-MakeMaker \
        python3 \
        mariadb-devel \
        dbus-devel \
        libbpf-devel \
        tar bzip2 \
    && dnf clean all

# Fetch the Slurm source tarball with integrity verification.
# The checksum must be updated when SLURM_VERSION changes.
ADD --checksum=sha256:237f515adcb37b99ff6cb3e1fa81691a5f7188e94c3b6b495858b4eaecf6531d \
    https://download.schedmd.com/slurm/slurm-${SLURM_VERSION}.tar.bz2 /tmp/slurm.tar.bz2

# Configure and install Slurm into a staging root so only the built
# artifacts are copied into the final image (no compiler toolchain).
WORKDIR /tmp
RUN tar xf slurm.tar.bz2 && \
    cd slurm-${SLURM_VERSION} && \
    ./configure \
        --prefix=/usr \
        --sysconfdir=/etc/slurm \
        --localstatedir=/var \
        --runstatedir=/run \
        --with-munge \
        --with-pam_dir=/usr/lib64/security \
        --with-systemdsystemunitdir=/usr/lib/systemd/system && \
    make -j$(nproc) && \
    DESTDIR=/slurm-install make install && \
    mkdir -p /slurm-install/etc

# ==============================================================================
# Stage 2: Runtime — lean image with only the packages needed at run time
# ==============================================================================
FROM quay.io/rockylinux/rockylinux:10

ARG SLURM_VERSION=25.11.4

RUN dnf -y install epel-release dnf-plugins-core && \
    dnf config-manager --set-enabled crb

# Runtime dependencies — no compilers or -devel packages.
# mariadb-server is included for the db role (slurmdbd accounting storage).
RUN dnf -y install \
        systemd \
        munge \
        mariadb-server \
        readline \
        pam \
        procps-ng \
        iproute \
        hostname \
        openssh-server \
        openssh-clients \
        dbus-libs \
    && dnf clean all

# Bring in only the compiled Slurm binaries, libraries, and config from the
# builder stage — keeps the final image small.
COPY --from=builder /slurm-install/usr /usr
COPY --from=builder /slurm-install/etc /etc

# Slurm daemons run as the unprivileged slurm user
RUN useradd -r -s /sbin/nologin slurm

# State directories for slurmctld and slurmd, plus the shared /data volume
RUN mkdir -p \
        /var/log/slurm \
        /var/spool/slurmctld \
        /var/spool/slurmd \
        /data && \
    chown -R slurm:slurm \
        /var/log/slurm \
        /var/spool/slurmctld \
        /var/spool/slurmd

# Munge requires strict ownership and permissions on its directories
RUN mkdir -p /etc/munge /var/lib/munge /var/log/munge /run/munge && \
    chown -R munge:munge /etc/munge /var/lib/munge /var/log/munge /run/munge && \
    chmod 700 /etc/munge /var/lib/munge /var/log/munge /run/munge

# Pre-generate SSH host keys and allow root login via pubkey only
# (sind injects authorized_keys at container start for inter-node SSH)
RUN ssh-keygen -A && \
    mkdir -p /run/sshd && \
    sed -i 's/#PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config && \
    sed -i 's/#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config && \
    mkdir -p /root/.ssh && chmod 700 /root/.ssh

# Only munge and sshd are enabled unconditionally — Slurm services
# (slurmctld, slurmdbd, slurmd) are enabled by sind at container start
# depending on the node's role.
RUN systemctl enable munge sshd

# Mask units that are unnecessary or problematic inside a container
RUN systemctl mask \
    dev-hugepages.mount \
    sys-fs-fuse-connections.mount \
    systemd-logind.service \
    getty.target \
    console-getty.service

LABEL org.opencontainers.image.title="sind-node" \
      org.opencontainers.image.description="Generic Slurm node for sind" \
      org.opencontainers.image.version="${SLURM_VERSION}" \
      sind.slurm.version="${SLURM_VERSION}"

VOLUME ["/etc/slurm", "/etc/munge", "/data"]
WORKDIR /data

# systemd expects SIGRTMIN+3 for a clean container shutdown
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
