// SPDX-License-Identifier: LGPL-3.0-or-later

package slurm

import (
	"fmt"
	"strings"
	"testing"

	"github.com/GSI-HPC/sind/pkg/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateSlurmConf(t *testing.T) {
	conf := GenerateSlurmConf("dev", config.Section{}, ConfOptions{})

	assert.Equal(t, "# Generated by sind\n"+
		"ClusterName=dev\n"+
		"SlurmctldHost=controller\n"+
		"SlurmUser=slurm\n"+
		"StateSaveLocation=/var/spool/slurmctld\n"+
		"SlurmdSpoolDir=/var/spool/slurmd\n"+
		"PlugStackConfig=/etc/slurm/plugstack.conf\n"+
		"\n"+
		"ProctrackType=proctrack/cgroup\n"+
		"TaskPlugin=task/cgroup\n"+
		"MpiDefault=pmix\n"+
		"ReturnToService=2\n"+
		"\n"+
		"include /etc/slurm/sind-nodes.conf\n", conf)
}

func TestGenerateSlurmConf_BaseOverrides(t *testing.T) {
	// A base parameter that slurm.main sets is not written twice.
	for _, main := range []config.Section{
		{Content: "TaskPlugin=task/cgroup,task/affinity\nMpiDefault=none\nProctrackType = proctrack/linuxproc\nReturnToService=1\n"},
		{Fragments: map[string]string{"a": "taskplugin=task/affinity\n", "b": "MpiDefault=none ProctrackType=proctrack/linuxproc ReturnToService=1\n"}},
	} {
		conf := GenerateSlurmConf("dev", main, ConfOptions{})
		for _, line := range []string{"TaskPlugin=task/cgroup", "MpiDefault=pmix", "ProctrackType=proctrack/cgroup", "ReturnToService=2"} {
			assert.NotContains(t, conf, "\n"+line+"\n")
		}
		// No empty block of defaults is left behind.
		assert.NotContains(t, conf, "\n\n\n")
	}
}

func TestGenerateSlurmConf_DefMemPerCPU(t *testing.T) {
	conf := GenerateSlurmConf("dev", config.Section{}, ConfOptions{DefMemPerCPU: 512})
	assert.Contains(t, conf, "\nReturnToService=2\nDefMemPerCPU=512\n")

	// slurm.main's DefMemPerCPU replaces it, and Slurm ignores
	// DefMemPerCPU next to DefMemPerNode.
	for _, main := range []string{"DefMemPerCPU=100\n", "DefMemPerNode=1024\n"} {
		conf = GenerateSlurmConf("dev", config.Section{Content: main}, ConfOptions{DefMemPerCPU: 512})
		assert.NotContains(t, conf, "DefMemPerCPU=512", main)
	}

	// None without workers.
	assert.NotContains(t, GenerateSlurmConf("dev", config.Section{}, ConfOptions{}), "DefMemPerCPU")
}

func TestTaskAffinity(t *testing.T) {
	assert.False(t, TaskAffinity(config.Section{}))
	assert.False(t, TaskAffinity(config.Section{Content: "TaskPlugin=task/cgroup\n"}))
	assert.True(t, TaskAffinity(config.Section{Content: "TaskPlugin=task/cgroup,task/affinity\n"}))
	assert.True(t, TaskAffinity(config.Section{Content: "TaskPlugin = cgroup,affinity # without prefix\n"}))
	assert.True(t, TaskAffinity(config.Section{Fragments: map[string]string{"tasks": "TaskPlugin=task/affinity\n"}}))
	assert.False(t, TaskAffinity(config.Section{Content: "TaskPlugin=task/affinity\nTaskPlugin=task/cgroup\n"}))
	assert.False(t, TaskAffinity(config.Section{Content: "TaskPluginParam=autobind=cores\n"}))
}

// confFiles serves the files of a config volume to ReadSlurmConf.
func confFiles(files map[string]string) func(string) (string, error) {
	return func(path string) (string, error) {
		content, ok := files[path]
		if !ok {
			return "", fmt.Errorf("cat: %s: No such file or directory", path)
		}
		return content, nil
	}
}

func TestReadSlurmConf(t *testing.T) {
	// Each include line gives way to the file it names: a relative path,
	// %c and a file without a final newline. sind-nodes.conf and globs are
	// left out.
	conf, err := ReadSlurmConf(confFiles(map[string]string{
		SlurmConfPath:            "ClusterName=Dev\ninclude site.conf # comment\nInclude /etc/slurm/*.conf\ninclude %c.conf\ninclude /etc/slurm/sind-nodes.conf\n",
		ConfDir + "/site.conf":   "MpiDefault=none",
		ConfDir + "/dev.conf":    "include /etc/slurm/nested.conf\nTaskPlugin=task/cgroup\n",
		ConfDir + "/nested.conf": "MaxJobCount=10\n",
		NodesConfPath:            "PartitionName=all Nodes=worker-0 Default=YES\n",
	}))
	require.NoError(t, err)
	assert.Equal(t, config.Section{Content: "ClusterName=Dev\nMpiDefault=none\nMaxJobCount=10\nTaskPlugin=task/cgroup\n"}, conf)
}

func TestEnablesTaskAffinity(t *testing.T) {
	// What sind generates, with and without slurm.main's TaskPlugin.
	for _, tt := range []struct {
		main config.Section
		want bool
	}{
		{config.Section{}, false},
		{config.Section{Content: "TaskPlugin=task/cgroup,task/affinity\n"}, true},
		{config.Section{Fragments: map[string]string{"tasks": "TaskPlugin=task/cgroup,task/affinity\n", "x": "MpiDefault=none\n"}}, true},
	} {
		files := map[string]string{SlurmConfPath: GenerateSlurmConf("dev", tt.main, ConfOptions{})}
		for name, content := range tt.main.Fragments {
			files[ConfDir+"/slurm.conf.d/"+name+".conf"] = content
		}
		conf, err := ReadSlurmConf(confFiles(files))
		require.NoError(t, err)
		assert.Equal(t, tt.want, EnablesTaskAffinity(conf), tt.main)
		assert.Equal(t, tt.want, TaskAffinity(tt.main), tt.main)
	}

	// Edited by hand: a later value wins over an included one.
	conf, err := ReadSlurmConf(confFiles(map[string]string{
		SlurmConfPath:          "include site.conf\nTaskPlugin=affinity,cgroup\n",
		ConfDir + "/site.conf": "TaskPlugin=task/cgroup\n",
	}))
	require.NoError(t, err)
	assert.True(t, EnablesTaskAffinity(conf))

	// Without a TaskPlugin there is no task plugin.
	assert.False(t, EnablesTaskAffinity(config.Section{Content: "ClusterName=dev\n"}))
}

func TestReadSlurmConf_Errors(t *testing.T) {
	_, err := ReadSlurmConf(confFiles(nil))
	require.EqualError(t, err, "reading /etc/slurm/slurm.conf: cat: /etc/slurm/slurm.conf: No such file or directory")

	_, err = ReadSlurmConf(confFiles(map[string]string{SlurmConfPath: "include missing.conf\n"}))
	require.EqualError(t, err, "reading /etc/slurm/missing.conf: cat: /etc/slurm/missing.conf: No such file or directory")

	_, err = ReadSlurmConf(confFiles(map[string]string{SlurmConfPath: "include slurm.conf\n"}))
	require.EqualError(t, err, "reading /etc/slurm/slurm.conf: includes nested more than 10 deep")
}

func TestGenerateSlurmConf_DefaultCluster(t *testing.T) {
	conf := GenerateSlurmConf("default", config.Section{}, ConfOptions{})

	assert.Contains(t, conf, "ClusterName=default")
	assert.Contains(t, conf, "SlurmctldHost=controller")
}

func TestGenerateSlurmConf_NoTrailingWhitespace(t *testing.T) {
	conf := GenerateSlurmConf("test", config.Section{}, ConfOptions{})
	for _, line := range strings.Split(conf, "\n") {
		assert.Equal(t, strings.TrimRight(line, " \t"), line,
			"line has trailing whitespace: %q", line)
	}
}

func TestGenerateSlurmConf_MainStringAppend(t *testing.T) {
	// The main section comes after the base config and before
	// sind-nodes.conf, so that its DEFAULT lines apply to sind's nodes and
	// partition; a missing final newline is added.
	main := config.Section{Content: "SchedulerType=sched/backfill\nPartitionName=DEFAULT DefaultTime=30"}
	conf := GenerateSlurmConf("dev", main, ConfOptions{})

	assert.True(t, strings.HasSuffix(conf, "ReturnToService=2\n\n"+
		"SchedulerType=sched/backfill\nPartitionName=DEFAULT DefaultTime=30\n"+
		"include /etc/slurm/sind-nodes.conf\n"), conf)
}

func TestGenerateSlurmConf_MainMapIncludes(t *testing.T) {
	main := config.Section{Fragments: map[string]string{
		"resources":  "SelectType=select/cons_tres\n",
		"scheduling": "SchedulerType=sched/backfill\n",
	}}
	conf := GenerateSlurmConf("dev", main, ConfOptions{})

	assert.True(t, strings.HasSuffix(conf, "\n\ninclude /etc/slurm/slurm.conf.d/resources.conf\n"+
		"include /etc/slurm/slurm.conf.d/scheduling.conf\n"+
		"include /etc/slurm/sind-nodes.conf\n"), conf)
	assert.NotContains(t, conf, "*")
}

func TestGenerateSlurmConf_SingleController(t *testing.T) {
	conf := GenerateSlurmConf("dev", config.Section{}, ConfOptions{})

	assert.Equal(t, 1, strings.Count(conf, "SlurmctldHost="))
	assert.NotContains(t, conf, "SlurmctldTimeout")
}

func TestGenerateSlurmConf_BackupController(t *testing.T) {
	conf := GenerateSlurmConf("dev", config.Section{}, ConfOptions{BackupController: true})

	assert.Contains(t, conf, "SlurmctldHost=controller\nSlurmctldHost=controller-backup\n")
	assert.Contains(t, conf, "SlurmctldTimeout=20\n")
	assert.Contains(t, conf, "StateSaveLocation=/var/spool/slurmctld\n")
}

func TestGenerateSlurmConf_BackupControllerTimeoutOverride(t *testing.T) {
	for _, main := range []config.Section{
		{Content: "SlurmctldTimeout=60\n"},
		{Fragments: map[string]string{"ha": "slurmctldtimeout=60\n"}},
	} {
		conf := GenerateSlurmConf("dev", main, ConfOptions{BackupController: true})
		assert.NotContains(t, conf, "SlurmctldTimeout=20")
	}
}

func TestGenerateSlurmConf_Accounting(t *testing.T) {
	conf := GenerateSlurmConf("dev", config.Section{}, ConfOptions{Accounting: true})

	assert.Contains(t, conf, "\nAccountingStorageType=accounting_storage/slurmdbd\n"+
		"AccountingStorageHost=db\n"+
		"JobAcctGatherType=jobacct_gather/cgroup\n")
	// The defaults come before the include so slurm.main can still add to them.
	assert.Less(t, strings.Index(conf, "AccountingStorageType"), strings.Index(conf, "include "))
}

func TestGenerateSlurmConf_Identity(t *testing.T) {
	local := GenerateSlurmConf("dev", config.Section{}, ConfOptions{Identity: config.IdentityLocal})
	for _, key := range []string{"LaunchParameters", "AuthType", "CredType", "AuthInfo"} {
		assert.NotContains(t, local, key)
	}
	assert.Equal(t, local, GenerateSlurmConf("dev", config.Section{}, ConfOptions{}))

	nss := GenerateSlurmConf("dev", config.Section{}, ConfOptions{Identity: config.IdentityNSSSlurm})
	assert.Contains(t, nss, "\nLaunchParameters=enable_nss_slurm\n")
	assert.NotContains(t, nss, "AuthType")

	// The identity settings come before the accounting ones and the
	// include, so slurm.main can still add to them.
	clientIDs := GenerateSlurmConf("dev", config.Section{}, ConfOptions{Identity: config.IdentityClientIDs, Accounting: true})
	assert.Contains(t, clientIDs, "\n\nAuthType=auth/slurm\n"+
		"CredType=cred/slurm\n"+
		"AuthInfo=use_client_ids\n"+
		"LaunchParameters=enable_nss_slurm\n"+
		"\nAccountingStorageType=accounting_storage/slurmdbd\n")
	assert.Less(t, strings.Index(clientIDs, "AuthType"), strings.Index(clientIDs, "include "))
}

func TestGenerateSlurmConf_IdentityOverrides(t *testing.T) {
	main := config.Section{Content: "LaunchParameters=enable_nss_slurm,use_interactive_step\nAuthInfo=use_client_ids,cred_expire=30\n"}
	conf := GenerateSlurmConf("dev", main, ConfOptions{Identity: config.IdentityClientIDs})

	assert.Contains(t, conf, "AuthType=auth/slurm\nCredType=cred/slurm\n\n")
	assert.Equal(t, 1, strings.Count(conf, "LaunchParameters="))
	assert.Equal(t, 1, strings.Count(conf, "AuthInfo="))
}

func TestGenerateSlurmConf_NoAccounting(t *testing.T) {
	conf := GenerateSlurmConf("dev", config.Section{}, ConfOptions{})

	assert.NotContains(t, conf, "AccountingStorage")
	assert.NotContains(t, conf, "JobAcctGather")
}

func TestGenerateSlurmConf_AccountingOverrides(t *testing.T) {
	for _, main := range []config.Section{
		{Content: "JobAcctGatherType=jobacct_gather/linux\n"},
		{Fragments: map[string]string{"acct": "jobacctgathertype=jobacct_gather/linux\n"}},
	} {
		conf := GenerateSlurmConf("dev", main, ConfOptions{Accounting: true})
		assert.Contains(t, conf, "AccountingStorageType=accounting_storage/slurmdbd\n")
		assert.Contains(t, conf, "AccountingStorageHost=db\n")
		assert.NotContains(t, conf, "JobAcctGatherType=jobacct_gather/cgroup")
	}
}

func TestGenerateSlurmdbdConf(t *testing.T) {
	conf := GenerateSlurmdbdConf(config.Section{}, config.IdentityLocal)

	assert.Equal(t, "# Generated by sind\n"+
		"AuthType=auth/munge\n"+
		"DbdHost=db\n"+
		"SlurmUser=slurm\n"+
		"LogFile=/var/log/slurm/slurmdbd.log\n"+
		"PidFile=/run/slurmdbd/slurmdbd.pid\n"+
		"\n"+
		"StorageType=accounting_storage/mysql\n"+
		"StorageHost=localhost\n"+
		"StorageLoc=slurm_acct_db\n"+
		"StorageUser=slurm\n", conf)
	assert.NotContains(t, conf, "StoragePass")
}

func TestGenerateSlurmdbdConf_ClientIDs(t *testing.T) {
	conf := GenerateSlurmdbdConf(config.Section{}, config.IdentityClientIDs)

	assert.True(t, strings.HasPrefix(conf, "# Generated by sind\n"+
		"AuthType=auth/slurm\n"+
		"AuthInfo=use_client_ids\n"+
		"DbdHost=db\n"))
	assert.NotContains(t, conf, "munge")
	// nssSlurm keeps munge.
	assert.Contains(t, GenerateSlurmdbdConf(config.Section{}, config.IdentityNSSSlurm), "AuthType=auth/munge\n")
}

func TestGenerateSlurmdbdConf_StringAppend(t *testing.T) {
	conf := GenerateSlurmdbdConf(config.Section{Content: "ArchiveEvents=yes\n"}, config.IdentityLocal)

	assert.True(t, strings.HasSuffix(conf, "StorageUser=slurm\nArchiveEvents=yes\n"))
}

func TestGenerateSlurmdbdConf_MapIncludes(t *testing.T) {
	conf := GenerateSlurmdbdConf(config.Section{Fragments: map[string]string{
		"purge":   "PurgeJobAfter=1month\n",
		"archive": "ArchiveEvents=yes\n",
	}}, config.IdentityLocal)

	assert.True(t, strings.HasSuffix(conf, "StorageUser=slurm\n"+
		"include /etc/slurm/slurmdbd.conf.d/archive.conf\n"+
		"include /etc/slurm/slurmdbd.conf.d/purge.conf\n"))
}

func TestGenerateCgroupConf(t *testing.T) {
	conf := GenerateCgroupConf(config.Section{})

	assert.Contains(t, conf, "CgroupPlugin=autodetect")
}

func TestGenerateCgroupConf_StringAppend(t *testing.T) {
	cgroup := config.Section{Content: "ConstrainCores=yes\n"}
	conf := GenerateCgroupConf(cgroup)

	assert.Contains(t, conf, "CgroupPlugin=autodetect")
	assert.Contains(t, conf, "ConstrainCores=yes\n")
}

func TestGenerateCgroupConf_MapIncludes(t *testing.T) {
	cgroup := config.Section{Fragments: map[string]string{
		"cores": "ConstrainCores=yes\n",
	}}
	conf := GenerateCgroupConf(cgroup)

	assert.Contains(t, conf, "CgroupPlugin=autodetect")
	assert.Contains(t, conf, "include /etc/slurm/cgroup.conf.d/cores.conf\n")
	assert.NotContains(t, conf, "*")
}

func TestGeneratePlugstackConf(t *testing.T) {
	conf := GeneratePlugstackConf(config.Section{})

	assert.Contains(t, conf, "include /etc/slurm/plugstack.conf.d/*")
}

func TestGeneratePlugstackConf_StringAppend(t *testing.T) {
	ps := config.Section{Content: "optional /usr/lib/slurm/spank_pbs.so\n"}
	conf := GeneratePlugstackConf(ps)

	assert.Contains(t, conf, "include /etc/slurm/plugstack.conf.d/*")
	assert.Contains(t, conf, "optional /usr/lib/slurm/spank_pbs.so\n")
}

func TestGenerateSectionConf(t *testing.T) {
	t.Run("string form", func(t *testing.T) {
		s := config.Section{Content: "Name=gpu Type=tesla\n"}
		conf := GenerateSectionConf("gres", s)

		assert.Equal(t, "Name=gpu Type=tesla\n", conf)
	})

	t.Run("map form", func(t *testing.T) {
		s := config.Section{Fragments: map[string]string{
			"gpu": "Name=gpu Type=tesla\n",
		}}
		conf := GenerateSectionConf("gres", s)

		assert.Equal(t, "include /etc/slurm/gres.conf.d/gpu.conf\n", conf)
	})
}
