// SPDX-License-Identifier: LGPL-3.0-or-later

package slurm

import (
	"strings"

	"github.com/GSI-HPC/sind/pkg/config"
)

// Service identifies a Slurm daemon managed by sind.
type Service string

// Slurm daemon services.
const (
	Slurmctld Service = "slurmctld"
	Slurmd    Service = "slurmd"
)

// ServiceForRole returns the Slurm service for the given node role.
// Returns empty string and false for roles that have no Slurm service.
func ServiceForRole(role config.Role) (Service, bool) {
	switch role {
	case config.RoleController:
		return Slurmctld, true
	case config.RoleWorker:
		return Slurmd, true
	default:
		return "", false
	}
}

// Container paths for Slurm configuration files.
const (
	ConfDir       = "/etc/slurm"
	NodesConfFile = "sind-nodes.conf"
	NodesConfPath = ConfDir + "/" + NodesConfFile
)

// GenerateSlurmConf generates the main slurm.conf content for a cluster.
// Node definitions are not included here; they go in sind-nodes.conf.
// The main section can append content (string form) or include a .conf.d
// directory (map form).
func GenerateSlurmConf(clusterName string, main config.Section) string {
	var b strings.Builder
	b.WriteString("# Generated by sind\n")
	b.WriteString("ClusterName=" + clusterName + "\n")
	b.WriteString("SlurmctldHost=controller\n")
	b.WriteString("SlurmUser=slurm\n")
	b.WriteString("StateSaveLocation=/var/spool/slurmctld\n")
	b.WriteString("SlurmdSpoolDir=/var/spool/slurmd\n")
	b.WriteString("\n")
	b.WriteString("ProctrackType=proctrack/cgroup\n")
	b.WriteString("TaskPlugin=task/cgroup,task/affinity\n")
	b.WriteString("ReturnToService=2\n")
	b.WriteString("PlugStackConfig=" + ConfDir + "/plugstack.conf\n")
	b.WriteString("\n")
	b.WriteString("include " + NodesConfPath + "\n")
	appendSection(&b, "slurm", main)
	return b.String()
}

// GenerateCgroupConf generates the cgroup.conf content for cgroupv2 support.
// The cgroup section can append content (string form) or include a .conf.d
// directory (map form).
func GenerateCgroupConf(cgroup config.Section) string {
	var b strings.Builder
	b.WriteString("# Generated by sind\n")
	b.WriteString("CgroupPlugin=autodetect\n")
	appendSection(&b, "cgroup", cgroup)
	return b.String()
}

// GeneratePlugstackConf generates the plugstack.conf content.
// Always includes the .conf.d directory for fragment support.
func GeneratePlugstackConf(plugstack config.Section) string {
	var b strings.Builder
	b.WriteString("# Generated by sind\n")
	b.WriteString("include " + ConfDir + "/plugstack.conf.d/*\n")
	if plugstack.Content != "" {
		b.WriteString(plugstack.Content)
	}
	return b.String()
}

// GenerateSectionConf generates the content for a standalone config file
// (gres.conf, topology.conf). String form returns content directly;
// map form returns an include directive for the .conf.d directory.
func GenerateSectionConf(name string, section config.Section) string {
	if section.IsMap() {
		return "include " + ConfDir + "/" + name + ".conf.d/*\n"
	}
	return section.Content
}

// appendSection appends section content to a config file builder.
// String form appends content directly; map form appends an include
// directive for the .conf.d directory.
func appendSection(b *strings.Builder, name string, s config.Section) {
	if s.IsEmpty() {
		return
	}
	if s.IsMap() {
		b.WriteString("include " + ConfDir + "/" + name + ".conf.d/*\n")
	} else {
		b.WriteString(s.Content)
	}
}
