// SPDX-License-Identifier: LGPL-3.0-or-later

package slurm

import "strings"

// GenerateSlurmConf generates the main slurm.conf content for a cluster.
// Node definitions are not included here; they go in sind-nodes.conf.
func GenerateSlurmConf(clusterName string) string {
	var b strings.Builder
	b.WriteString("# Generated by sind\n")
	b.WriteString("ClusterName=" + clusterName + "\n")
	b.WriteString("SlurmctldHost=controller\n")
	b.WriteString("\n")
	b.WriteString("ProctrackType=proctrack/cgroup\n")
	b.WriteString("TaskPlugin=task/cgroup,task/affinity\n")
	b.WriteString("ReturnToService=2\n")
	b.WriteString("\n")
	b.WriteString("include /etc/slurm/sind-nodes.conf\n")
	return b.String()
}
