// SPDX-License-Identifier: LGPL-3.0-or-later

package slurm

import (
	"strconv"
	"strings"

	"github.com/GSI-HPC/sind/pkg/config"
)

// Container paths for Slurm configuration files.
const (
	ConfDir          = "/etc/slurm"
	NodesConfFile    = "sind-nodes.conf"
	NodesConfPath    = ConfDir + "/" + NodesConfFile
	SlurmdbdConfFile = "slurmdbd.conf"
	SlurmdbdConfPath = ConfDir + "/" + SlurmdbdConfFile
)

// Accounting: the db node's hostname and the MariaDB database and user
// slurmdbd stores accounting data in.
const (
	DBHost       = "db"
	AccountingDB = "slurm_acct_db"
	StorageUser  = "slurm"
)

// Controller hostnames and the slurmctld state directory.
const (
	ControllerHost       = "controller"
	BackupControllerHost = "controller-backup"
	StateSaveLocation    = "/var/spool/slurmctld"
)

// DefaultSlurmctldTimeout is the SlurmctldTimeout sind writes for a
// primary/backup controller pair, in seconds. Slurm's default of 120s makes
// failover tests needlessly slow; users can override it in the main section.
const DefaultSlurmctldTimeout = 20

// ConfOptions selects the optional parts of the generated slurm.conf.
type ConfOptions struct {
	// BackupController configures controller-backup as the backup
	// controller of a primary/backup pair.
	BackupController bool
	// Accounting sends accounting data to the slurmdbd on a managed db node
	// and gathers per-job resource usage.
	Accounting bool
	// Identity adds the settings of the identity modes other than local:
	// nss_slurm for both, and auth/slurm with client IDs for clientIds.
	Identity config.IdentityMode
}

// parameter is a slurm.conf parameter sind sets unless the main section
// sets it.
type parameter struct{ key, value string }

// accountingDefaults are the slurm.conf parameters sind sets when the
// cluster has a managed db node, in output order.
var accountingDefaults = []parameter{
	{"AccountingStorageType", "accounting_storage/slurmdbd"},
	{"AccountingStorageHost", DBHost},
	{"JobAcctGatherType", "jobacct_gather/cgroup"},
}

// identityDefaults returns the slurm.conf parameters of an identity mode
// (see config.IdentityMode.SlurmParameters).
func identityDefaults(mode config.IdentityMode) []parameter {
	var defaults []parameter
	for _, p := range mode.SlurmParameters() {
		defaults = append(defaults, parameter{p.Key, p.Value})
	}
	return defaults
}

// writeDefaults writes a blank line and each parameter that the main
// section does not set, if there are any parameters.
func writeDefaults(b *strings.Builder, main config.Section, defaults []parameter) {
	if len(defaults) == 0 {
		return
	}
	b.WriteString("\n")
	for _, p := range defaults {
		if !main.SetsParameter(p.key) {
			b.WriteString(p.key + "=" + p.value + "\n")
		}
	}
}

// GenerateSlurmConf generates the main slurm.conf content for a cluster.
// Node definitions are not included here; they go in sind-nodes.conf.
// The main section can append content (string form) or include a .conf.d
// directory (map form).
//
// With opts.BackupController, controller-backup is configured as the backup
// controller and SlurmctldTimeout defaults to DefaultSlurmctldTimeout unless
// the main section sets it. With opts.Accounting, the accounting parameters
// in accountingDefaults are added, and with opts.Identity those of the
// identity mode, each unless the main section sets it.
func GenerateSlurmConf(clusterName string, main config.Section, opts ConfOptions) string {
	var b strings.Builder
	b.WriteString("# Generated by sind\n")
	b.WriteString("ClusterName=" + clusterName + "\n")
	b.WriteString("SlurmctldHost=" + ControllerHost + "\n")
	if opts.BackupController {
		b.WriteString("SlurmctldHost=" + BackupControllerHost + "\n")
		if !main.SetsParameter("SlurmctldTimeout") {
			b.WriteString("SlurmctldTimeout=" + strconv.Itoa(DefaultSlurmctldTimeout) + "\n")
		}
	}
	b.WriteString("SlurmUser=slurm\n")
	b.WriteString("StateSaveLocation=" + StateSaveLocation + "\n")
	b.WriteString("SlurmdSpoolDir=/var/spool/slurmd\n")
	b.WriteString("\n")
	b.WriteString("ProctrackType=proctrack/cgroup\n")
	b.WriteString("TaskPlugin=task/cgroup,task/affinity\n")
	b.WriteString("MpiDefault=pmix\n")
	b.WriteString("ReturnToService=2\n")
	b.WriteString("PlugStackConfig=" + ConfDir + "/plugstack.conf\n")
	writeDefaults(&b, main, identityDefaults(opts.Identity))
	if opts.Accounting {
		writeDefaults(&b, main, accountingDefaults)
	}
	b.WriteString("\n")
	b.WriteString("include " + NodesConfPath + "\n")
	appendSection(&b, "slurm", main)
	return b.String()
}

// GenerateSlurmdbdConf generates slurmdbd.conf for the db node: slurmdbd
// runs as SlurmUser and stores accounting data in the local MariaDB as
// StorageUser, which MariaDB authenticates by unix_socket as the OS user
// slurmdbd runs as, or by the StoragePass the slurmdbd section sets. It
// authenticates with munge, or with identity clientIds with auth/slurm and
// the users' client IDs, as slurmctld does. The slurmdbd section can append
// content (string form) or include .conf.d fragments (map form).
//
// The pid file lives in /run/slurmdbd, the RuntimeDirectory slurmdbd.service
// creates for the slurm user: /run itself is not writable for it. sind
// writes no StoragePass line, since slurmdbd rejects an empty value.
func GenerateSlurmdbdConf(slurmdbd config.Section, identity config.IdentityMode) string {
	var b strings.Builder
	b.WriteString("# Generated by sind\n")
	if identity == config.IdentityClientIDs {
		b.WriteString("AuthType=auth/slurm\n")
		b.WriteString("AuthInfo=use_client_ids\n")
	} else {
		b.WriteString("AuthType=auth/munge\n")
	}
	b.WriteString("DbdHost=" + DBHost + "\n")
	b.WriteString("SlurmUser=slurm\n")
	b.WriteString("LogFile=/var/log/slurm/slurmdbd.log\n")
	b.WriteString("PidFile=/run/slurmdbd/slurmdbd.pid\n")
	b.WriteString("\n")
	b.WriteString("StorageType=accounting_storage/mysql\n")
	b.WriteString("StorageHost=localhost\n")
	b.WriteString("StorageLoc=" + AccountingDB + "\n")
	b.WriteString("StorageUser=" + StorageUser + "\n")
	appendSection(&b, "slurmdbd", slurmdbd)
	return b.String()
}

// GenerateCgroupConf generates the cgroup.conf content for cgroupv2 support.
// The cgroup section can append content (string form) or include a .conf.d
// directory (map form).
func GenerateCgroupConf(cgroup config.Section) string {
	var b strings.Builder
	b.WriteString("# Generated by sind\n")
	b.WriteString("CgroupPlugin=autodetect\n")
	appendSection(&b, "cgroup", cgroup)
	return b.String()
}

// GeneratePlugstackConf generates the plugstack.conf content.
// Always includes the .conf.d directory for fragment support.
func GeneratePlugstackConf(plugstack config.Section) string {
	var b strings.Builder
	b.WriteString("# Generated by sind\n")
	b.WriteString("include " + ConfDir + "/plugstack.conf.d/*\n")
	if plugstack.Content != "" {
		b.WriteString(plugstack.Content)
	}
	return b.String()
}

// GenerateSectionConf generates the content for a standalone config file
// (gres.conf, topology.conf). String form returns content directly;
// map form returns include lines for each fragment file.
func GenerateSectionConf(name string, section config.Section) string {
	if section.IsMap() {
		var b strings.Builder
		appendFragmentIncludes(&b, name, section)
		return b.String()
	}
	return section.Content
}

// appendSection appends section content to a config file builder.
// String form appends content directly; map form appends an include
// line for each fragment file (Slurm does not support glob includes).
func appendSection(b *strings.Builder, name string, s config.Section) {
	if s.IsEmpty() {
		return
	}
	if s.IsMap() {
		appendFragmentIncludes(b, name, s)
	} else {
		b.WriteString(s.Content)
	}
}

// appendFragmentIncludes writes an include line for each fragment file
// in sorted order.
func appendFragmentIncludes(b *strings.Builder, name string, s config.Section) {
	for _, key := range s.FragmentNames() {
		b.WriteString("include " + ConfDir + "/" + name + ".conf.d/" + key + ".conf\n")
	}
}
