// SPDX-License-Identifier: LGPL-3.0-or-later

package slurm

import (
	"fmt"
	"strings"

	"github.com/GSI-HPC/sind/pkg/config"
)

// ManagedWorkers returns the sind-nodes.conf entries of a cluster's managed
// workers, in config order. Workers are named worker-0, worker-1, ...
// across all worker groups, unmanaged ones included, which get no entry.
// The Slurm CPUs and RealMemory of a worker are its container's CPU and
// memory limits; a memory limit that config.MemoryMB rejects is an error.
func ManagedWorkers(nodes []config.Node) ([]NodeEntry, error) {
	var workers []NodeEntry
	idx := 0
	for _, n := range nodes {
		if n.Role != config.RoleWorker {
			continue
		}
		count := max(n.Count, 1)
		first := idx
		idx += count
		if n.Managed != nil && !*n.Managed {
			continue
		}
		memMB, err := config.MemoryMB(n.Memory)
		if err != nil {
			return nil, fmt.Errorf("worker-%d: invalid memory %q: %w", first, n.Memory, err)
		}
		for i := first; i < idx; i++ {
			workers = append(workers, NodeEntry{Name: fmt.Sprintf("worker-%d", i), CPUs: n.CPUs, MemoryMB: memMB})
		}
	}
	return workers, nil
}

// GenerateNodesConf generates the sind-nodes.conf content with a NodeName
// line for each managed worker (see ManagedWorkers) and the partition all
// with every one of them.
func GenerateNodesConf(workers []NodeEntry) string {
	var b strings.Builder
	b.WriteString("# Generated by sind\n")
	names := make([]string, 0, len(workers))
	for _, w := range workers {
		fmt.Fprintf(&b, "NodeName=%s CPUs=%d RealMemory=%d State=UNKNOWN\n", w.Name, w.CPUs, w.MemoryMB)
		names = append(names, w.Name)
	}
	if len(names) > 0 {
		fmt.Fprintf(&b, "PartitionName=all Nodes=%s Default=YES MaxTime=INFINITE State=UP\n",
			strings.Join(names, ","))
	}
	return b.String()
}

// NodeEntry represents a single node to add to sind-nodes.conf.
type NodeEntry struct {
	Name     string
	CPUs     int
	MemoryMB int
}

// AddNodesToConf adds node definitions to existing sind-nodes.conf content.
// A node that already has a NodeName line, such as one a failed
// `sind create worker` left behind, gets its line replaced, as Slurm
// refuses to start with a node defined twice; the other nodes get new
// lines. The PartitionName Nodes= list is updated to include both existing
// and new nodes, each once.
func AddNodesToConf(existing string, nodes []NodeEntry) string {
	lines := strings.Split(strings.TrimRight(existing, "\n"), "\n")

	added := make(map[string]string, len(nodes))
	for _, n := range nodes {
		added[n.Name] = fmt.Sprintf("NodeName=%s CPUs=%d RealMemory=%d State=UNKNOWN",
			n.Name, n.CPUs, n.MemoryMB)
	}

	var managed []string
	var kept []string
	listed := make(map[string]bool)

	for _, line := range lines {
		if strings.HasPrefix(line, "PartitionName=") {
			continue // will be regenerated
		}
		name, isNode := nodeName(line)
		if !isNode {
			kept = append(kept, line)
			continue
		}
		if listed[name] {
			continue // a duplicate definition
		}
		listed[name] = true
		managed = append(managed, name)
		if def, ok := added[name]; ok {
			line = def
		}
		kept = append(kept, line)
	}

	for _, n := range nodes {
		if listed[n.Name] {
			continue
		}
		listed[n.Name] = true
		kept = append(kept, added[n.Name])
		managed = append(managed, n.Name)
	}

	if len(managed) > 0 {
		kept = append(kept, fmt.Sprintf("PartitionName=all Nodes=%s Default=YES MaxTime=INFINITE State=UP",
			strings.Join(managed, ",")))
	}

	return strings.Join(kept, "\n") + "\n"
}

// nodeName returns the node a NodeName line defines, and whether line is
// one.
func nodeName(line string) (string, bool) {
	if !strings.HasPrefix(line, "NodeName=") {
		return "", false
	}
	return strings.TrimPrefix(strings.Fields(line)[0], "NodeName="), true
}

// RemoveNodesFromConf removes the named nodes from existing sind-nodes.conf
// content. NodeName lines for the removed nodes are deleted and the
// PartitionName Nodes= list is updated.
func RemoveNodesFromConf(existing string, names []string) string {
	remove := make(map[string]bool, len(names))
	for _, n := range names {
		remove[n] = true
	}

	lines := strings.Split(strings.TrimRight(existing, "\n"), "\n")

	var managed []string
	var kept []string

	for _, line := range lines {
		if strings.HasPrefix(line, "PartitionName=") {
			continue // will be regenerated
		}
		if name, isNode := nodeName(line); isNode {
			if remove[name] {
				continue // skip removed node
			}
			managed = append(managed, name)
		}
		kept = append(kept, line)
	}

	if len(managed) > 0 {
		kept = append(kept, fmt.Sprintf("PartitionName=all Nodes=%s Default=YES MaxTime=INFINITE State=UP",
			strings.Join(managed, ",")))
	}

	return strings.Join(kept, "\n") + "\n"
}

// ParseMemoryMB parses a memory limit in Docker's size syntax (e.g. "2g",
// "512m", "1.5GiB") and returns it in megabytes (see config.MemoryMB).
func ParseMemoryMB(s string) (int, error) {
	return config.MemoryMB(s)
}
