// SPDX-License-Identifier: LGPL-3.0-or-later

package slurm

import (
	"fmt"
	"slices"
	"strings"

	"github.com/GSI-HPC/sind/pkg/config"
)

// ManagedWorkers returns the sind-nodes.conf entries of a cluster's managed
// workers, in config order. Workers are named worker-0, worker-1, ...
// across all worker groups, unmanaged ones included, which get no entry.
// The Slurm CPUs and RealMemory of a worker are its container's CPU and
// memory limits; a memory limit that config.MemoryMB rejects is an error.
func ManagedWorkers(nodes []config.Node) ([]NodeEntry, error) {
	var workers []NodeEntry
	idx := 0
	for _, n := range nodes {
		if n.Role != config.RoleWorker {
			continue
		}
		count := max(n.Count, 1)
		first := idx
		idx += count
		if n.Managed != nil && !*n.Managed {
			continue
		}
		memMB, err := config.MemoryMB(n.Memory)
		if err != nil {
			return nil, fmt.Errorf("worker-%d: invalid memory %q: %w", first, n.Memory, err)
		}
		for i := first; i < idx; i++ {
			workers = append(workers, NodeEntry{Name: fmt.Sprintf("worker-%d", i), CPUs: n.CPUs, MemoryMB: memMB})
		}
	}
	return workers, nil
}

// DefMemPerCPU returns the default memory per allocated CPU, in MB, that
// lets every managed worker run a job on each of its CPUs: the smallest
// RealMemory/CPUs over the workers, rounded down. Slurm's default
// select/cons_tres treats memory as a consumable resource, and without a
// default a job that does not ask for memory gets all of a node's memory,
// so a worker would run one such job at a time whatever its CPUs. It
// returns 0, for none, without workers or with a worker that has less
// than 1 MB per CPU.
func DefMemPerCPU(workers []NodeEntry) int {
	perCPU, found := 0, false
	for _, w := range workers {
		if m := w.MemoryMB / max(w.CPUs, 1); !found || m < perCPU {
			perCPU, found = m, true
		}
	}
	return perCPU
}

// GenerateNodesConf generates the sind-nodes.conf content with a NodeName
// line for each managed worker (see ManagedWorkers) and the partition all
// with every one of them. Partition all is the default partition unless
// the main section declares another one (see declaresDefaultPartition):
// slurm.conf includes sind-nodes.conf after the main section, and of
// several default partitions slurmctld takes the last.
func GenerateNodesConf(workers []NodeEntry, main config.Section) string {
	var b strings.Builder
	b.WriteString("# Generated by sind\n")
	names := make([]string, 0, len(workers))
	for _, w := range workers {
		fmt.Fprintf(&b, "NodeName=%s CPUs=%d RealMemory=%d State=UNKNOWN\n", w.Name, w.CPUs, w.MemoryMB)
		names = append(names, w.Name)
	}
	if len(names) > 0 {
		b.WriteString(newPartitionLine(names, !declaresDefaultPartition(main)) + "\n")
	}
	return b.String()
}

// newPartitionLine returns the line of partition all with the given nodes.
// It sets only Default, so that PartitionName=DEFAULT lines in the main
// section apply to everything else, such as MaxTime and State, whose Slurm
// defaults are INFINITE and UP.
func newPartitionLine(nodes []string, isDefault bool) string {
	flag := "YES"
	if !isDefault {
		flag = "NO"
	}
	return "PartitionName=all Nodes=" + strings.Join(nodes, ",") + " Default=" + flag
}

// partitionLine returns the line of partition all with the given nodes:
// old, the partition's earlier line, with its Nodes= list replaced, so that
// other changes to the line survive, or a new default partition without
// one.
func partitionLine(old string, nodes []string) string {
	if old == "" {
		return newPartitionLine(nodes, true)
	}
	list := "Nodes=" + strings.Join(nodes, ",")
	fields := strings.Fields(old)
	for i, f := range fields {
		if key, _, _ := strings.Cut(f, "="); strings.EqualFold(key, "Nodes") {
			fields[i] = list
			return strings.Join(fields, " ")
		}
	}
	return strings.Join(append(fields, list), " ")
}

// declaresDefaultPartition reports whether the main section declares a
// default partition of its own: a PartitionName line, other than
// PartitionName=DEFAULT, with a true Default (YES, UP, TRUE or 1).
func declaresDefaultPartition(main config.Section) bool {
	for line := range main.Lines() {
		pairs := config.LinePairs(line)
		if len(pairs) == 0 || !strings.EqualFold(pairs[0][0], "PartitionName") || strings.EqualFold(pairs[0][1], "DEFAULT") {
			continue
		}
		for _, p := range pairs[1:] {
			if strings.EqualFold(p[0], "Default") && slices.ContainsFunc([]string{"yes", "up", "true", "1"}, func(v string) bool { return strings.EqualFold(v, p[1]) }) {
				return true
			}
		}
	}
	return false
}

// NodeEntry represents a single node to add to sind-nodes.conf.
type NodeEntry struct {
	Name     string
	CPUs     int
	MemoryMB int
}

// AddNodesToConf adds node definitions to existing sind-nodes.conf content.
// A node that already has a NodeName line, such as one a failed
// `sind create worker` left behind, gets its line replaced, as Slurm
// refuses to start with a node defined twice; the other nodes get new
// lines. The PartitionName Nodes= list is updated to include both existing
// and new nodes, each once; the rest of the partition line stays (see
// partitionLine).
func AddNodesToConf(existing string, nodes []NodeEntry) string {
	lines := strings.Split(strings.TrimRight(existing, "\n"), "\n")

	added := make(map[string]string, len(nodes))
	for _, n := range nodes {
		added[n.Name] = fmt.Sprintf("NodeName=%s CPUs=%d RealMemory=%d State=UNKNOWN",
			n.Name, n.CPUs, n.MemoryMB)
	}

	var managed []string
	var kept []string
	listed := make(map[string]bool)
	var partition string

	for _, line := range lines {
		if strings.HasPrefix(line, "PartitionName=") {
			partition = line
			continue // will be regenerated
		}
		name, isNode := nodeName(line)
		if !isNode {
			kept = append(kept, line)
			continue
		}
		if listed[name] {
			continue // a duplicate definition
		}
		listed[name] = true
		managed = append(managed, name)
		if def, ok := added[name]; ok {
			line = def
		}
		kept = append(kept, line)
	}

	for _, n := range nodes {
		if listed[n.Name] {
			continue
		}
		listed[n.Name] = true
		kept = append(kept, added[n.Name])
		managed = append(managed, n.Name)
	}

	if len(managed) > 0 {
		kept = append(kept, partitionLine(partition, managed))
	}

	return strings.Join(kept, "\n") + "\n"
}

// nodeName returns the node a NodeName line defines, and whether line is
// one.
func nodeName(line string) (string, bool) {
	if !strings.HasPrefix(line, "NodeName=") {
		return "", false
	}
	return strings.TrimPrefix(strings.Fields(line)[0], "NodeName="), true
}

// RemoveNodesFromConf removes the named nodes from existing sind-nodes.conf
// content. NodeName lines for the removed nodes are deleted and the
// PartitionName Nodes= list is updated; the rest of the partition line
// stays (see partitionLine).
func RemoveNodesFromConf(existing string, names []string) string {
	remove := make(map[string]bool, len(names))
	for _, n := range names {
		remove[n] = true
	}

	lines := strings.Split(strings.TrimRight(existing, "\n"), "\n")

	var managed []string
	var kept []string
	var partition string

	for _, line := range lines {
		if strings.HasPrefix(line, "PartitionName=") {
			partition = line
			continue // will be regenerated
		}
		if name, isNode := nodeName(line); isNode {
			if remove[name] {
				continue // skip removed node
			}
			managed = append(managed, name)
		}
		kept = append(kept, line)
	}

	if len(managed) > 0 {
		kept = append(kept, partitionLine(partition, managed))
	}

	return strings.Join(kept, "\n") + "\n"
}

// ParseMemoryMB parses a memory limit in Docker's size syntax (e.g. "2g",
// "512m", "1.5GiB") and returns it in megabytes (see config.MemoryMB).
func ParseMemoryMB(s string) (int, error) {
	return config.MemoryMB(s)
}
