// SPDX-License-Identifier: LGPL-3.0-or-later

package slurm

import (
	"strings"
	"testing"

	"github.com/GSI-HPC/sind/internal/testutil"
	"github.com/GSI-HPC/sind/pkg/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateNodesConf_Minimal(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", CPUs: 2, Memory: "2g"},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, conf, "PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP")
}

func TestGenerateNodesConf_MultiCompute(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "4g"},
		{Role: "worker", Count: 3, CPUs: 4, Memory: "8g"},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "NodeName=worker-0 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=worker-1 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=worker-2 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "PartitionName=all Nodes=worker-0,worker-1,worker-2 Default=YES MaxTime=INFINITE State=UP")
}

func TestGenerateNodesConf_MultipleGroups(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", Count: 2, CPUs: 2, Memory: "2g"},
		{Role: "worker", Count: 2, CPUs: 4, Memory: "8g"},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=worker-1 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=worker-2 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=worker-3 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "Nodes=worker-0,worker-1,worker-2,worker-3")
}

func TestGenerateNodesConf_SkipsUnmanaged(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", Count: 2, CPUs: 2, Memory: "2g"},
		{Role: "worker", Count: 2, CPUs: 2, Memory: "2g", Managed: testutil.Ptr(false)},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "NodeName=worker-0")
	assert.Contains(t, conf, "NodeName=worker-1")
	assert.NotContains(t, conf, "worker-2")
	assert.NotContains(t, conf, "worker-3")
	assert.Contains(t, conf, "Nodes=worker-0,worker-1")
}

func TestGenerateNodesConf_SkipsNonCompute(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "submitter", CPUs: 2, Memory: "2g"},
		{Role: "worker", CPUs: 2, Memory: "2g"},
	}

	conf := generateNodesConf(t, nodes)

	assert.NotContains(t, conf, "controller")
	assert.NotContains(t, conf, "submitter")
	assert.Contains(t, conf, "NodeName=worker-0")
}

func TestGenerateNodesConf_AllUnmanaged(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", Count: 2, CPUs: 2, Memory: "2g", Managed: testutil.Ptr(false)},
	}

	conf := generateNodesConf(t, nodes)

	assert.NotContains(t, conf, "NodeName=")
	assert.NotContains(t, conf, "PartitionName=")
}

func TestGenerateNodesConf_ExplicitManaged(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", CPUs: 2, Memory: "2g", Managed: testutil.Ptr(true)},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "NodeName=worker-0")
	assert.Contains(t, conf, "PartitionName=all Nodes=worker-0")
}

func TestGenerateNodesConf_EmptyInput(t *testing.T) {
	conf := generateNodesConf(t, nil)

	assert.NotContains(t, conf, "NodeName=")
	assert.NotContains(t, conf, "PartitionName=")
}

func TestGenerateNodesConf_MemoryMB(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", CPUs: 2, Memory: "512m"},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "RealMemory=512")
}

// --- AddNodesToConf ---

func TestAddNodesToConf_AppendOne(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-1", CPUs: 4, MemoryMB: 8192},
	})

	assert.Contains(t, result, "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, result, "NodeName=worker-1 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, result, "PartitionName=all Nodes=worker-0,worker-1 Default=YES MaxTime=INFINITE State=UP")
}

func TestAddNodesToConf_AppendMultiple(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-1", CPUs: 2, MemoryMB: 2048},
		{Name: "worker-2", CPUs: 2, MemoryMB: 2048},
	})

	assert.Contains(t, result, "Nodes=worker-0,worker-1,worker-2")
}

func TestAddNodesToConf_PreservesComment(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-1", CPUs: 2, MemoryMB: 2048},
	})

	assert.True(t, len(result) > 0)
	lines := splitLines(result)
	assert.Equal(t, "# Generated by sind", lines[0])
}

func TestAddNodesToConf_ReplacesExistingNode(t *testing.T) {
	// A node a failed add left behind is defined once, with the new values:
	// Slurm refuses to start with a node defined twice.
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=1 RealMemory=512 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-1 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-1", CPUs: 4, MemoryMB: 8192},
		{Name: "worker-2", CPUs: 4, MemoryMB: 8192},
	})

	assert.Equal(t, "# Generated by sind\n"+
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n"+
		"NodeName=worker-1 CPUs=4 RealMemory=8192 State=UNKNOWN\n"+
		"NodeName=worker-2 CPUs=4 RealMemory=8192 State=UNKNOWN\n"+
		"PartitionName=all Nodes=worker-0,worker-1,worker-2 Default=YES MaxTime=INFINITE State=UP\n", result)
}

func TestAddNodesToConf_DropsDuplicates(t *testing.T) {
	// Duplicate definitions, as earlier sind versions could leave, and
	// duplicate new entries are written once.
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=1 RealMemory=512 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=2 RealMemory=1024 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-0,worker-1,worker-1 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-1", CPUs: 4, MemoryMB: 8192},
		{Name: "worker-2", CPUs: 4, MemoryMB: 8192},
		{Name: "worker-2", CPUs: 4, MemoryMB: 8192},
	})

	assert.Equal(t, "# Generated by sind\n"+
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n"+
		"NodeName=worker-1 CPUs=4 RealMemory=8192 State=UNKNOWN\n"+
		"NodeName=worker-2 CPUs=4 RealMemory=8192 State=UNKNOWN\n"+
		"PartitionName=all Nodes=worker-0,worker-1,worker-2 Default=YES MaxTime=INFINITE State=UP\n", result)
}

func TestRemoveNodesFromConf_RemovesDuplicates(t *testing.T) {
	existing := "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=1 RealMemory=512 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=2 RealMemory=1024 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-1,worker-1 Default=YES MaxTime=INFINITE State=UP\n"

	result := RemoveNodesFromConf(existing, []string{"worker-1"})

	assert.Equal(t, "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n"+
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n", result)
}

func TestNodesConf_RemoveUnlistedNodeChangesNothing(t *testing.T) {
	// What sind generates comes back unchanged when the nodes to remove are
	// not in it, which lets WorkerRemove skip the write and reconfigure.
	workers, err := ManagedWorkers([]config.Node{{Role: config.RoleWorker, Count: 2, CPUs: 2, Memory: "2g"}})
	require.NoError(t, err)
	conf := GenerateNodesConf(workers)
	added := AddNodesToConf(conf, []NodeEntry{{Name: "worker-2", CPUs: 1, MemoryMB: 512}})

	assert.Equal(t, conf, RemoveNodesFromConf(conf, []string{"worker-7"}))
	assert.Equal(t, conf, RemoveNodesFromConf(added, []string{"worker-2"}))
}

func TestAddNodesToConf_NoExistingPartition(t *testing.T) {
	existing := "# Generated by sind\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-0", CPUs: 2, MemoryMB: 2048},
	})

	assert.Contains(t, result, "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, result, "PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP")
}

func splitLines(s string) []string {
	s = strings.TrimRight(s, "\n")
	return strings.Split(s, "\n")
}

// --- RemoveNodesFromConf ---

func TestRemoveNodesFromConf_RemoveOne(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-1 Default=YES MaxTime=INFINITE State=UP\n"

	result := RemoveNodesFromConf(existing, []string{"worker-1"})

	assert.Contains(t, result, "NodeName=worker-0")
	assert.NotContains(t, result, "worker-1")
	assert.Contains(t, result, "PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP")
}

func TestRemoveNodesFromConf_RemoveAll(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := RemoveNodesFromConf(existing, []string{"worker-0"})

	assert.NotContains(t, result, "NodeName=")
	assert.NotContains(t, result, "PartitionName=")
	assert.Contains(t, result, "# Generated by sind")
}

func TestRemoveNodesFromConf_PreservesOthers(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=4 RealMemory=8192 State=UNKNOWN\n" +
		"NodeName=worker-2 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-1,worker-2 Default=YES MaxTime=INFINITE State=UP\n"

	result := RemoveNodesFromConf(existing, []string{"worker-1"})

	assert.Contains(t, result, "NodeName=worker-0")
	assert.NotContains(t, result, "NodeName=worker-1")
	assert.Contains(t, result, "NodeName=worker-2")
	assert.Contains(t, result, "Nodes=worker-0,worker-2")
}

// generateNodesConf generates sind-nodes.conf for the managed workers of
// nodes.
func generateNodesConf(t *testing.T, nodes []config.Node) string {
	t.Helper()
	workers, err := ManagedWorkers(nodes)
	require.NoError(t, err)
	return GenerateNodesConf(workers)
}

// --- ManagedWorkers ---

func TestManagedWorkers(t *testing.T) {
	workers, err := ManagedWorkers([]config.Node{
		{Role: "controller", CPUs: 1, Memory: "bogus"},
		{Role: "worker", Count: 2, CPUs: 2, Memory: "1.5g"},
		{Role: "worker", CPUs: 1, Memory: "bogus", Managed: testutil.Ptr(false)},
		{Role: "worker", CPUs: 4, Memory: "2GiB"},
	})
	require.NoError(t, err)
	assert.Equal(t, []NodeEntry{
		{Name: "worker-0", CPUs: 2, MemoryMB: 1536},
		{Name: "worker-1", CPUs: 2, MemoryMB: 1536},
		{Name: "worker-3", CPUs: 4, MemoryMB: 2048},
	}, workers)
}

func TestManagedWorkers_InvalidMemory(t *testing.T) {
	// A memory limit sind cannot convert is an error, never RealMemory=0.
	_, err := ManagedWorkers([]config.Node{
		{Role: "worker", Count: 2, CPUs: 1, Memory: "512m"},
		{Role: "worker", CPUs: 1, Memory: "2x"},
	})
	require.ErrorContains(t, err, `worker-2: invalid memory "2x"`)
}

// --- ParseMemoryMB ---

func TestParseMemoryMB(t *testing.T) {
	got, err := ParseMemoryMB("2gb")
	require.NoError(t, err)
	assert.Equal(t, 2048, got)

	_, err = ParseMemoryMB("2x")
	assert.Error(t, err)
}
