// SPDX-License-Identifier: LGPL-3.0-or-later

package slurm

import (
	"strings"
	"testing"

	"github.com/GSI-HPC/sind/internal/testutil"
	"github.com/GSI-HPC/sind/pkg/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateNodesConf_Minimal(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", CPUs: 2, Memory: "2g"},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, conf, "PartitionName=all Nodes=worker-0 Default=YES\n")
}

func TestGenerateNodesConf_MultiCompute(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "4g"},
		{Role: "worker", Count: 3, CPUs: 4, Memory: "8g"},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "NodeName=worker-0 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=worker-1 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=worker-2 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "PartitionName=all Nodes=worker-0,worker-1,worker-2 Default=YES\n")
}

func TestGenerateNodesConf_MultipleGroups(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", Count: 2, CPUs: 2, Memory: "2g"},
		{Role: "worker", Count: 2, CPUs: 4, Memory: "8g"},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=worker-1 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=worker-2 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=worker-3 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "Nodes=worker-0,worker-1,worker-2,worker-3")
}

func TestGenerateNodesConf_SkipsUnmanaged(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", Count: 2, CPUs: 2, Memory: "2g"},
		{Role: "worker", Count: 2, CPUs: 2, Memory: "2g", Managed: testutil.Ptr(false)},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "NodeName=worker-0")
	assert.Contains(t, conf, "NodeName=worker-1")
	assert.NotContains(t, conf, "worker-2")
	assert.NotContains(t, conf, "worker-3")
	assert.Contains(t, conf, "Nodes=worker-0,worker-1")
}

func TestGenerateNodesConf_SkipsNonCompute(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "submitter", CPUs: 2, Memory: "2g"},
		{Role: "worker", CPUs: 2, Memory: "2g"},
	}

	conf := generateNodesConf(t, nodes)

	assert.NotContains(t, conf, "controller")
	assert.NotContains(t, conf, "submitter")
	assert.Contains(t, conf, "NodeName=worker-0")
}

func TestGenerateNodesConf_AllUnmanaged(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", Count: 2, CPUs: 2, Memory: "2g", Managed: testutil.Ptr(false)},
	}

	conf := generateNodesConf(t, nodes)

	assert.NotContains(t, conf, "NodeName=")
	assert.NotContains(t, conf, "PartitionName=")
}

func TestGenerateNodesConf_ExplicitManaged(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", CPUs: 2, Memory: "2g", Managed: testutil.Ptr(true)},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "NodeName=worker-0")
	assert.Contains(t, conf, "PartitionName=all Nodes=worker-0")
}

func TestGenerateNodesConf_EmptyInput(t *testing.T) {
	conf := generateNodesConf(t, nil)

	assert.NotContains(t, conf, "NodeName=")
	assert.NotContains(t, conf, "PartitionName=")
}

func TestGenerateNodesConf_MemoryMB(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "worker", CPUs: 2, Memory: "512m"},
	}

	conf := generateNodesConf(t, nodes)

	assert.Contains(t, conf, "RealMemory=512")
}

// --- AddNodesToConf ---

func TestAddNodesToConf_AppendOne(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-1", CPUs: 4, MemoryMB: 8192},
	}, config.Section{})

	assert.Contains(t, result, "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, result, "NodeName=worker-1 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, result, "PartitionName=all Nodes=worker-0,worker-1 Default=YES MaxTime=INFINITE State=UP")
}

func TestAddNodesToConf_AppendMultiple(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-1", CPUs: 2, MemoryMB: 2048},
		{Name: "worker-2", CPUs: 2, MemoryMB: 2048},
	}, config.Section{})

	assert.Contains(t, result, "Nodes=worker-0,worker-1,worker-2")
}

func TestAddNodesToConf_PreservesComment(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-1", CPUs: 2, MemoryMB: 2048},
	}, config.Section{})

	assert.True(t, len(result) > 0)
	lines := splitLines(result)
	assert.Equal(t, "# Generated by sind", lines[0])
}

func TestAddNodesToConf_ReplacesExistingNode(t *testing.T) {
	// A node a failed add left behind is defined once, with the new values:
	// Slurm refuses to start with a node defined twice.
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=1 RealMemory=512 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-1 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-1", CPUs: 4, MemoryMB: 8192},
		{Name: "worker-2", CPUs: 4, MemoryMB: 8192},
	}, config.Section{})

	assert.Equal(t, "# Generated by sind\n"+
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n"+
		"NodeName=worker-1 CPUs=4 RealMemory=8192 State=UNKNOWN\n"+
		"NodeName=worker-2 CPUs=4 RealMemory=8192 State=UNKNOWN\n"+
		"PartitionName=all Nodes=worker-0,worker-1,worker-2 Default=YES MaxTime=INFINITE State=UP\n", result)
}

func TestAddNodesToConf_DropsDuplicates(t *testing.T) {
	// Duplicate definitions, as earlier sind versions could leave, and
	// duplicate new entries are written once.
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=1 RealMemory=512 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=2 RealMemory=1024 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-0,worker-1,worker-1 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-1", CPUs: 4, MemoryMB: 8192},
		{Name: "worker-2", CPUs: 4, MemoryMB: 8192},
		{Name: "worker-2", CPUs: 4, MemoryMB: 8192},
	}, config.Section{})

	assert.Equal(t, "# Generated by sind\n"+
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n"+
		"NodeName=worker-1 CPUs=4 RealMemory=8192 State=UNKNOWN\n"+
		"NodeName=worker-2 CPUs=4 RealMemory=8192 State=UNKNOWN\n"+
		"PartitionName=all Nodes=worker-0,worker-1,worker-2 Default=YES MaxTime=INFINITE State=UP\n", result)
}

func TestRemoveNodesFromConf_RemovesDuplicates(t *testing.T) {
	existing := "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=1 RealMemory=512 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=2 RealMemory=1024 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-1,worker-1 Default=YES MaxTime=INFINITE State=UP\n"

	result := RemoveNodesFromConf(existing, []string{"worker-1"})

	assert.Equal(t, "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n"+
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n", result)
}

func TestNodesConf_RemoveUnlistedNodeChangesNothing(t *testing.T) {
	// What sind generates comes back unchanged when the nodes to remove are
	// not in it, which lets WorkerRemove skip the write and reconfigure.
	workers, err := ManagedWorkers([]config.Node{{Role: config.RoleWorker, Count: 2, CPUs: 2, Memory: "2g"}})
	require.NoError(t, err)
	conf := GenerateNodesConf(workers, config.Section{})
	added := AddNodesToConf(conf, []NodeEntry{{Name: "worker-2", CPUs: 1, MemoryMB: 512}}, config.Section{})

	assert.Equal(t, conf, RemoveNodesFromConf(conf, []string{"worker-7"}))
	assert.Equal(t, conf, RemoveNodesFromConf(added, []string{"worker-2"}))
}

func TestAddNodesToConf_NoExistingPartition(t *testing.T) {
	existing := "# Generated by sind\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "worker-0", CPUs: 2, MemoryMB: 2048},
	}, config.Section{})

	assert.Contains(t, result, "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, result, "PartitionName=all Nodes=worker-0 Default=YES\n")
}

func TestAddNodesToConf_NewPartitionKeepsMainDefault(t *testing.T) {
	// Partition all, written again after the last managed worker took it
	// along, does not become the default when slurm.conf declares one of
	// its own: it would win, as sind-nodes.conf comes last.
	main := config.Section{Content: "PartitionName=debug Nodes=ALL Default=YES\n"}
	workers := []NodeEntry{{Name: "worker-0", CPUs: 1, MemoryMB: 512}}
	created := GenerateNodesConf(workers, main)
	require.Contains(t, created, "PartitionName=all Nodes=worker-0 Default=NO\n")
	emptied := RemoveNodesFromConf(created, []string{"worker-0"})
	require.Equal(t, "# Generated by sind\n", emptied)

	conf, err := ReadSlurmConf(confFiles(map[string]string{SlurmConfPath: GenerateSlurmConf("dev", main, ConfOptions{})}))
	require.NoError(t, err)
	result := AddNodesToConf(emptied, []NodeEntry{{Name: "worker-1", CPUs: 1, MemoryMB: 512}}, conf)
	assert.Equal(t, "# Generated by sind\n"+
		"NodeName=worker-1 CPUs=1 RealMemory=512 State=UNKNOWN\n"+
		"PartitionName=all Nodes=worker-1 Default=NO\n", result)
}

func TestAddNodesToConf_KeepsPartitionLine(t *testing.T) {
	// Only the Nodes= list changes: Default=NO, written when slurm.main
	// declares its own default partition, and edits made by hand stay.
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0 Default=NO DefaultTime=10\n"

	result := AddNodesToConf(existing, []NodeEntry{{Name: "worker-1", CPUs: 2, MemoryMB: 2048}}, config.Section{})
	assert.Contains(t, result, "PartitionName=all Nodes=worker-0,worker-1 Default=NO DefaultTime=10\n")

	result = RemoveNodesFromConf(result, []string{"worker-0"})
	assert.Contains(t, result, "PartitionName=all Nodes=worker-1 Default=NO DefaultTime=10\n")
}

func TestPartitionLine(t *testing.T) {
	assert.Equal(t, "PartitionName=all Nodes=worker-1 Default=NO", partitionLine("PartitionName=all nodes=worker-0 Default=NO", []string{"worker-1"}))
	// A line edited to lose its Nodes= gets them back at the end.
	assert.Equal(t, "PartitionName=all Default=NO Nodes=worker-1", partitionLine("PartitionName=all  Default=NO", []string{"worker-1"}))
}

func splitLines(s string) []string {
	s = strings.TrimRight(s, "\n")
	return strings.Split(s, "\n")
}

// --- RemoveNodesFromConf ---

func TestRemoveNodesFromConf_RemoveOne(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-1 Default=YES MaxTime=INFINITE State=UP\n"

	result := RemoveNodesFromConf(existing, []string{"worker-1"})

	assert.Contains(t, result, "NodeName=worker-0")
	assert.NotContains(t, result, "worker-1")
	assert.Contains(t, result, "PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP")
}

func TestRemoveNodesFromConf_RemoveAll(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := RemoveNodesFromConf(existing, []string{"worker-0"})

	assert.NotContains(t, result, "NodeName=")
	assert.NotContains(t, result, "PartitionName=")
	assert.Contains(t, result, "# Generated by sind")
}

func TestRemoveNodesFromConf_NoPartitionLine(t *testing.T) {
	// Without a partition line, as when it was removed by hand, the nodes
	// left get none.
	existing := "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=2 RealMemory=2048 State=UNKNOWN\n"

	result := RemoveNodesFromConf(existing, []string{"worker-1"})

	assert.Equal(t, "NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n", result)
}

func TestRemoveNodesFromConf_PreservesOthers(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=4 RealMemory=8192 State=UNKNOWN\n" +
		"NodeName=worker-2 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-1,worker-2 Default=YES MaxTime=INFINITE State=UP\n"

	result := RemoveNodesFromConf(existing, []string{"worker-1"})

	assert.Contains(t, result, "NodeName=worker-0")
	assert.NotContains(t, result, "NodeName=worker-1")
	assert.Contains(t, result, "NodeName=worker-2")
	assert.Contains(t, result, "Nodes=worker-0,worker-2")
}

// generateNodesConf generates sind-nodes.conf for the managed workers of
// nodes.
func generateNodesConf(t *testing.T, nodes []config.Node) string {
	t.Helper()
	workers, err := ManagedWorkers(nodes)
	require.NoError(t, err)
	return GenerateNodesConf(workers, config.Section{})
}

// --- ManagedWorkers ---

func TestManagedWorkers(t *testing.T) {
	workers, err := ManagedWorkers([]config.Node{
		{Role: "controller", CPUs: 1, Memory: "bogus"},
		{Role: "worker", Count: 2, CPUs: 2, Memory: "1.5g"},
		{Role: "worker", CPUs: 1, Memory: "bogus", Managed: testutil.Ptr(false)},
		{Role: "worker", CPUs: 4, Memory: "2GiB"},
	})
	require.NoError(t, err)
	assert.Equal(t, []NodeEntry{
		{Name: "worker-0", CPUs: 2, MemoryMB: 1536},
		{Name: "worker-1", CPUs: 2, MemoryMB: 1536},
		{Name: "worker-3", CPUs: 4, MemoryMB: 2048},
	}, workers)
}

func TestManagedWorkers_InvalidMemory(t *testing.T) {
	// A memory limit sind cannot convert is an error, never RealMemory=0.
	_, err := ManagedWorkers([]config.Node{
		{Role: "worker", Count: 2, CPUs: 1, Memory: "512m"},
		{Role: "worker", CPUs: 1, Memory: "2x"},
	})
	require.ErrorContains(t, err, `worker-2: invalid memory "2x"`)
}

func TestGenerateNodesConf_MainDefaultPartition(t *testing.T) {
	// A default partition of slurm.main's own stays the default, although
	// sind-nodes.conf comes after it: partition all is not the default.
	workers := []NodeEntry{{Name: "worker-0", CPUs: 1, MemoryMB: 512}}
	for _, tt := range []struct {
		main string
		want string
	}{
		{"", "Default=YES"},
		{"PartitionName=debug Nodes=ALL Default=YES\n", "Default=NO"},
		{"PartitionName=debug Nodes=ALL default=true MaxTime=30\n", "Default=NO"},
		{"PartitionName=debug Nodes=ALL Default=1\n", "Default=NO"},
		{"PartitionName=debug Nodes=ALL Default=UP\n", "Default=NO"},
		{"PartitionName=debug Nodes=ALL Default=NO\n", "Default=YES"},
		{"PartitionName=debug Nodes=ALL # Default=YES\n", "Default=YES"},
		{"PartitionName=DEFAULT Default=YES DefaultTime=10\n", "Default=YES"},
		{"NodeName=n1 Default=YES\n", "Default=YES"},
		{"Default=YES\n", "Default=YES"},
	} {
		conf := GenerateNodesConf(workers, config.Section{Content: tt.main})
		assert.Contains(t, conf, "PartitionName=all Nodes=worker-0 "+tt.want+"\n", tt.main)
	}

	frag := config.Section{Fragments: map[string]string{"a": "MaxNodeCount=10\n", "b": "PartitionName=debug Nodes=ALL Default=YES\n"}}
	assert.Contains(t, GenerateNodesConf(workers, frag), "Default=NO\n")
}

// --- DefMemPerCPU ---

func TestDefMemPerCPU(t *testing.T) {
	assert.Equal(t, 0, DefMemPerCPU(nil))
	assert.Equal(t, 512, DefMemPerCPU([]NodeEntry{{Name: "worker-0", CPUs: 1, MemoryMB: 512}}))
	// The smallest memory per CPU of all workers, rounded down.
	assert.Equal(t, 341, DefMemPerCPU([]NodeEntry{
		{Name: "worker-0", CPUs: 2, MemoryMB: 2048},
		{Name: "worker-1", CPUs: 3, MemoryMB: 1024},
		{Name: "worker-2", CPUs: 1, MemoryMB: 512},
	}))
	// No default when a worker has less than 1 MB per CPU.
	assert.Equal(t, 0, DefMemPerCPU([]NodeEntry{
		{Name: "worker-0", CPUs: 8, MemoryMB: 6},
		{Name: "worker-1", CPUs: 1, MemoryMB: 512},
	}))
	// A worker without CPUs (no ApplyDefaults) counts as one CPU.
	assert.Equal(t, 512, DefMemPerCPU([]NodeEntry{{Name: "worker-0", MemoryMB: 512}}))
}

// --- ParseMemoryMB ---

func TestParseMemoryMB(t *testing.T) {
	got, err := ParseMemoryMB("2gb")
	require.NoError(t, err)
	assert.Equal(t, 2048, got)

	_, err = ParseMemoryMB("2x")
	assert.Error(t, err)
}
