// SPDX-License-Identifier: LGPL-3.0-or-later

package slurm

import (
	"strings"
	"testing"

	"github.com/GSI-HPC/sind/pkg/config"
	"github.com/stretchr/testify/assert"
)

func boolPtr(b bool) *bool { return &b }

func TestGenerateNodesConf_Minimal(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "compute", CPUs: 2, Memory: "2g"},
	}

	conf := GenerateNodesConf(nodes)

	assert.Contains(t, conf, "NodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, conf, "PartitionName=all Nodes=compute-0 Default=YES MaxTime=INFINITE State=UP")
}

func TestGenerateNodesConf_MultiCompute(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "4g"},
		{Role: "compute", Count: 3, CPUs: 4, Memory: "8g"},
	}

	conf := GenerateNodesConf(nodes)

	assert.Contains(t, conf, "NodeName=compute-0 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=compute-1 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=compute-2 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "PartitionName=all Nodes=compute-0,compute-1,compute-2 Default=YES MaxTime=INFINITE State=UP")
}

func TestGenerateNodesConf_MultipleGroups(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "compute", Count: 2, CPUs: 2, Memory: "2g"},
		{Role: "compute", Count: 2, CPUs: 4, Memory: "8g"},
	}

	conf := GenerateNodesConf(nodes)

	assert.Contains(t, conf, "NodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=compute-1 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=compute-2 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "NodeName=compute-3 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, conf, "Nodes=compute-0,compute-1,compute-2,compute-3")
}

func TestGenerateNodesConf_SkipsUnmanaged(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "compute", Count: 2, CPUs: 2, Memory: "2g"},
		{Role: "compute", Count: 2, CPUs: 2, Memory: "2g", Managed: boolPtr(false)},
	}

	conf := GenerateNodesConf(nodes)

	assert.Contains(t, conf, "NodeName=compute-0")
	assert.Contains(t, conf, "NodeName=compute-1")
	assert.NotContains(t, conf, "compute-2")
	assert.NotContains(t, conf, "compute-3")
	assert.Contains(t, conf, "Nodes=compute-0,compute-1")
}

func TestGenerateNodesConf_SkipsNonCompute(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "submitter", CPUs: 2, Memory: "2g"},
		{Role: "compute", CPUs: 2, Memory: "2g"},
	}

	conf := GenerateNodesConf(nodes)

	assert.NotContains(t, conf, "controller")
	assert.NotContains(t, conf, "submitter")
	assert.Contains(t, conf, "NodeName=compute-0")
}

func TestGenerateNodesConf_AllUnmanaged(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "compute", Count: 2, CPUs: 2, Memory: "2g", Managed: boolPtr(false)},
	}

	conf := GenerateNodesConf(nodes)

	assert.NotContains(t, conf, "NodeName=")
	assert.NotContains(t, conf, "PartitionName=")
}

func TestGenerateNodesConf_ExplicitManaged(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "compute", CPUs: 2, Memory: "2g", Managed: boolPtr(true)},
	}

	conf := GenerateNodesConf(nodes)

	assert.Contains(t, conf, "NodeName=compute-0")
	assert.Contains(t, conf, "PartitionName=all Nodes=compute-0")
}

func TestGenerateNodesConf_EmptyInput(t *testing.T) {
	conf := GenerateNodesConf(nil)

	assert.NotContains(t, conf, "NodeName=")
	assert.NotContains(t, conf, "PartitionName=")
}

func TestGenerateNodesConf_MemoryMB(t *testing.T) {
	nodes := []config.Node{
		{Role: "controller", CPUs: 2, Memory: "2g"},
		{Role: "compute", CPUs: 2, Memory: "512m"},
	}

	conf := GenerateNodesConf(nodes)

	assert.Contains(t, conf, "RealMemory=512")
}

// --- AddNodesToConf ---

func TestAddNodesToConf_AppendOne(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=compute-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "compute-1", CPUs: 4, MemoryMB: 8192},
	})

	assert.Contains(t, result, "NodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, result, "NodeName=compute-1 CPUs=4 RealMemory=8192 State=UNKNOWN")
	assert.Contains(t, result, "PartitionName=all Nodes=compute-0,compute-1 Default=YES MaxTime=INFINITE State=UP")
}

func TestAddNodesToConf_AppendMultiple(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=compute-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "compute-1", CPUs: 2, MemoryMB: 2048},
		{Name: "compute-2", CPUs: 2, MemoryMB: 2048},
	})

	assert.Contains(t, result, "Nodes=compute-0,compute-1,compute-2")
}

func TestAddNodesToConf_PreservesComment(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=compute-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "compute-1", CPUs: 2, MemoryMB: 2048},
	})

	assert.True(t, len(result) > 0)
	lines := splitLines(result)
	assert.Equal(t, "# Generated by sind", lines[0])
}

func TestAddNodesToConf_NoExistingPartition(t *testing.T) {
	existing := "# Generated by sind\n"

	result := AddNodesToConf(existing, []NodeEntry{
		{Name: "compute-0", CPUs: 2, MemoryMB: 2048},
	})

	assert.Contains(t, result, "NodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN")
	assert.Contains(t, result, "PartitionName=all Nodes=compute-0 Default=YES MaxTime=INFINITE State=UP")
}

func splitLines(s string) []string {
	s = strings.TrimRight(s, "\n")
	return strings.Split(s, "\n")
}

// --- RemoveNodesFromConf ---

func TestRemoveNodesFromConf_RemoveOne(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=compute-1 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=compute-0,compute-1 Default=YES MaxTime=INFINITE State=UP\n"

	result := RemoveNodesFromConf(existing, []string{"compute-1"})

	assert.Contains(t, result, "NodeName=compute-0")
	assert.NotContains(t, result, "compute-1")
	assert.Contains(t, result, "PartitionName=all Nodes=compute-0 Default=YES MaxTime=INFINITE State=UP")
}

func TestRemoveNodesFromConf_RemoveAll(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=compute-0 Default=YES MaxTime=INFINITE State=UP\n"

	result := RemoveNodesFromConf(existing, []string{"compute-0"})

	assert.NotContains(t, result, "NodeName=")
	assert.NotContains(t, result, "PartitionName=")
	assert.Contains(t, result, "# Generated by sind")
}

func TestRemoveNodesFromConf_PreservesOthers(t *testing.T) {
	existing := "# Generated by sind\n" +
		"NodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=compute-1 CPUs=4 RealMemory=8192 State=UNKNOWN\n" +
		"NodeName=compute-2 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=compute-0,compute-1,compute-2 Default=YES MaxTime=INFINITE State=UP\n"

	result := RemoveNodesFromConf(existing, []string{"compute-1"})

	assert.Contains(t, result, "NodeName=compute-0")
	assert.NotContains(t, result, "NodeName=compute-1")
	assert.Contains(t, result, "NodeName=compute-2")
	assert.Contains(t, result, "Nodes=compute-0,compute-2")
}

// --- parseMemoryMB ---

func TestParseMemoryMB(t *testing.T) {
	tests := []struct {
		input string
		want  int
	}{
		{"2g", 2048},
		{"4g", 4096},
		{"512m", 512},
		{"1024m", 1024},
		{"2G", 2048},
		{"512M", 512},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got, err := parseMemoryMB(tt.input)
			assert.NoError(t, err)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestParseMemoryMB_Zero(t *testing.T) {
	got, err := parseMemoryMB("0g")
	assert.NoError(t, err)
	assert.Equal(t, 0, got)

	got, err = parseMemoryMB("0m")
	assert.NoError(t, err)
	assert.Equal(t, 0, got)
}

func TestParseMemoryMB_Invalid(t *testing.T) {
	tests := []string{"", "abc", "2x", "g", "xm"}

	for _, input := range tests {
		t.Run(input, func(t *testing.T) {
			_, err := parseMemoryMB(input)
			assert.Error(t, err)
		})
	}
}
