// SPDX-License-Identifier: LGPL-3.0-or-later

package slurm

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/GSI-HPC/sind/pkg/config"
)

// GenerateNodesConf generates the sind-nodes.conf content with NodeName and
// PartitionName directives. Only managed compute nodes are included.
// Non-compute nodes and unmanaged compute nodes are skipped.
func GenerateNodesConf(nodes []config.Node) string {
	var b strings.Builder
	var managed []string
	idx := 0

	b.WriteString("# Generated by sind\n")

	for _, n := range nodes {
		if n.Role != "compute" {
			continue
		}

		count := n.Count
		if count <= 0 {
			count = 1
		}

		memMB, _ := parseMemoryMB(n.Memory)

		for i := 0; i < count; i++ {
			name := fmt.Sprintf("compute-%d", idx)
			idx++

			if n.Managed != nil && !*n.Managed {
				continue
			}

			b.WriteString(fmt.Sprintf("NodeName=%s CPUs=%d RealMemory=%d State=UNKNOWN\n",
				name, n.CPUs, memMB))
			managed = append(managed, name)
		}
	}

	if len(managed) > 0 {
		b.WriteString(fmt.Sprintf("PartitionName=all Nodes=%s Default=YES MaxTime=INFINITE State=UP\n",
			strings.Join(managed, ",")))
	}

	return b.String()
}

// parseMemoryMB parses a Docker-style memory string (e.g. "2g", "512m") and
// returns the value in megabytes.
func parseMemoryMB(s string) (int, error) {
	if len(s) == 0 {
		return 0, fmt.Errorf("empty memory string")
	}

	suffix := s[len(s)-1]
	numStr := s[:len(s)-1]

	switch suffix {
	case 'g', 'G':
		n, err := strconv.Atoi(numStr)
		if err != nil {
			return 0, fmt.Errorf("invalid memory value: %q", s)
		}
		return n * 1024, nil
	case 'm', 'M':
		n, err := strconv.Atoi(numStr)
		if err != nil {
			return 0, fmt.Errorf("invalid memory value: %q", s)
		}
		return n, nil
	default:
		return 0, fmt.Errorf("unsupported memory suffix in %q, use 'm' or 'g'", s)
	}
}
