// SPDX-License-Identifier: LGPL-3.0-or-later

package cluster

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/GSI-HPC/sind/pkg/docker"
	"github.com/GSI-HPC/sind/pkg/mesh"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// inspectJSONLabels builds docker inspect JSON output with custom labels.
func inspectJSONLabels(t *testing.T, name, status string, networks map[docker.NetworkName]string, labels map[string]string) string {
	t.Helper()
	type netInfo struct {
		IPAddress string `json:"IPAddress"`
	}
	type result struct {
		ID    string `json:"Id"`
		Name  string `json:"Name"`
		State struct {
			Status string `json:"Status"`
		} `json:"State"`
		Config struct {
			Labels map[string]string `json:"Labels"`
		} `json:"Config"`
		NetworkSettings struct {
			Networks map[string]netInfo `json:"Networks"`
		} `json:"NetworkSettings"`
	}
	r := result{ID: "id-" + name, Name: "/" + name}
	r.State.Status = status
	r.Config.Labels = labels
	nets := make(map[string]netInfo)
	for n, ip := range networks {
		nets[string(n)] = netInfo{IPAddress: ip}
	}
	r.NetworkSettings.Networks = nets
	data, err := json.Marshal([]result{r})
	require.NoError(t, err)
	return string(data)
}

// workerContainers returns a standard set of cluster containers for worker tests.
func workerContainers(computes ...string) string {
	entries := []psEntry{
		{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
			Labels: "sind.cluster=dev,sind.role=controller"},
	}
	for _, c := range computes {
		entries = append(entries, psEntry{
			ID: "c" + c, Names: "sind-dev-" + c, State: "running", Image: "img:1",
			Labels: "sind.cluster=dev,sind.role=compute",
		})
	}
	return ndjson(entries...)
}

// --- ValidateWorkerAdd ---

func TestWorkerAdd_RequiresSindNodes(t *testing.T) {
	// When sind-nodes.conf is missing on the controller,
	// managed worker add must fail.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		// ListContainers: controller exists
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ndjson(
				psEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
			)}
		}
		// ReadFile (docker exec controller cat /etc/slurm/sind-nodes.conf) fails
		if args[0] == "exec" && len(args) >= 4 && args[2] == "cat" {
			return docker.MockResult{Err: fmt.Errorf("cat: /etc/slurm/sind-nodes.conf: No such file or directory")}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "sind-nodes.conf")
}

func TestWorkerAdd_RequiresSindNodes_Present(t *testing.T) {
	// When sind-nodes.conf exists, validation passes for managed workers.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ndjson(
				psEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
			)}
		}
		if args[0] == "exec" && len(args) >= 4 && args[2] == "cat" {
			return docker.MockResult{Stdout: "# Generated by sind\nNodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n"}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.NoError(t, err)
}

func TestWorkerAdd_AllowsUnmanaged(t *testing.T) {
	// Unmanaged worker add bypasses sind-nodes.conf check.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ndjson(
				psEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
			)}
		}
		// Should never reach ReadFile for unmanaged
		if args[0] == "exec" {
			return docker.MockResult{Err: fmt.Errorf("should not be called")}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		Unmanaged:   true,
	})

	require.NoError(t, err)
}

func TestWorkerAdd_ClusterNotFound(t *testing.T) {
	// If no controller container exists for the cluster, validation fails.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ""}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "controller not found")
}

func TestWorkerAdd_ClusterNotFound_Unmanaged(t *testing.T) {
	// Even unmanaged mode requires the cluster (controller) to exist.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ""}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		Unmanaged:   true,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "controller not found")
}

func TestWorkerAdd_ListContainersError(t *testing.T) {
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Err: fmt.Errorf("docker daemon not running")}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "listing cluster containers")
}

// --- NextComputeIndex ---

func TestNextComputeIndex_Empty(t *testing.T) {
	// No compute containers → next index is 0.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ndjson(
				psEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
			)}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	idx, err := NextComputeIndex(context.Background(), client, "dev")

	require.NoError(t, err)
	assert.Equal(t, 0, idx)
}

func TestNextComputeIndex_Sequential(t *testing.T) {
	// compute-0 and compute-1 exist → next index is 2.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: workerContainers("compute-0", "compute-1")}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	idx, err := NextComputeIndex(context.Background(), client, "dev")

	require.NoError(t, err)
	assert.Equal(t, 2, idx)
}

func TestNextComputeIndex_Gap(t *testing.T) {
	// compute-0 and compute-3 exist → next index is 4 (fills after max).
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: workerContainers("compute-0", "compute-3")}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	idx, err := NextComputeIndex(context.Background(), client, "dev")

	require.NoError(t, err)
	assert.Equal(t, 4, idx)
}

func TestNextComputeIndex_NonComputeIgnored(t *testing.T) {
	// Controller and submitter don't affect compute index.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ndjson(
				psEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
				psEntry{ID: "def", Names: "sind-dev-submitter", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=submitter"},
			)}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	idx, err := NextComputeIndex(context.Background(), client, "dev")

	require.NoError(t, err)
	assert.Equal(t, 0, idx)
}

func TestNextComputeIndex_ListError(t *testing.T) {
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Err: fmt.Errorf("docker daemon not running")}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	_, err := NextComputeIndex(context.Background(), client, "dev")

	require.Error(t, err)
	assert.Contains(t, err.Error(), "listing cluster containers")
}

// --- WorkerAdd (managed) ---

// workerAddOnCall returns a mock OnCall handler for the WorkerAdd managed flow.
// The cluster has 1 controller + 1 existing compute (compute-0).
// The new worker will be compute-1.
func workerAddOnCall(t *testing.T) func([]string, string) docker.MockResult {
	t.Helper()

	nodesConf := "# Generated by sind\n" +
		"NodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=compute-0 Default=YES MaxTime=INFINITE State=UP\n"

	return func(args []string, stdin string) docker.MockResult {
		if len(args) == 0 {
			return docker.MockResult{}
		}
		joined := strings.Join(args, " ")

		switch {
		// ListContainers: cluster has controller + compute-0
		case args[0] == "ps":
			return docker.MockResult{Stdout: workerContainers("compute-0")}

		// InspectContainer: sind-dns → return mesh IP
		case args[0] == "inspect" && args[1] == "sind-dns":
			return docker.MockResult{Stdout: inspectJSON(t, "sind-dns", "running", map[docker.NetworkName]string{
				"sind-mesh": "10.0.0.2",
			})}

		// InspectContainer: controller → return slurm version label
		case args[0] == "inspect" && args[1] == "sind-dev-controller":
			return docker.MockResult{Stdout: inspectJSONLabels(t, "sind-dev-controller", "running",
				map[docker.NetworkName]string{"sind-dev-net": "10.0.1.1"},
				map[string]string{"sind.slurm.version": "25.11.0"})}

		// InspectContainer: new compute node
		case args[0] == "inspect" && strings.HasPrefix(args[1], "sind-dev-compute-"):
			return docker.MockResult{Stdout: inspectJSON(t, args[1], "running", map[docker.NetworkName]string{
				"sind-dev-net": "10.0.1.3",
			})}

		// ReadFile: SSH pubkey from sind-ssh
		case args[0] == "exec" && args[1] == "sind-ssh" && len(args) > 2 && args[2] == "cat":
			return docker.MockResult{Stdout: "ssh-ed25519 AAAA-test-key\n"}

		// ReadFile: sind-nodes.conf (for validation and update)
		case args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "cat":
			return docker.MockResult{Stdout: nodesConf}

		// WriteFile: updated sind-nodes.conf
		case args[0] == "exec" && args[1] == "-i" && strings.Contains(joined, "sind-dev-controller"):
			return docker.MockResult{}

		// scontrol reconfigure
		case args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "scontrol":
			return docker.MockResult{}

		// CreateContainer
		case args[0] == "create":
			return docker.MockResult{Stdout: "new-cid\n"}

		// ConnectNetwork (mesh)
		case args[0] == "network" && args[1] == "connect":
			return docker.MockResult{}

		// StartContainer
		case args[0] == "start":
			return docker.MockResult{}

		// Exec on new compute: probes, SSH inject, host key, systemctl
		case args[0] == "exec":
			container := args[1]
			if container == "-i" {
				// ExecWithStdin (SSH key inject, WriteFile)
				return docker.MockResult{}
			}
			if len(args) > 2 {
				switch cmd := args[2]; {
				case cmd == "sh" && strings.Contains(joined, "is-system-running"):
					return docker.MockResult{Stdout: "running\n"}
				case cmd == "bash" && strings.Contains(joined, "/dev/tcp"):
					return docker.MockResult{Stdout: "SSH-2.0-OpenSSH_9.0\n"}
				case cmd == "mkdir":
					return docker.MockResult{}
				case cmd == "ssh-keyscan":
					return docker.MockResult{Stdout: "localhost ssh-ed25519 AAAA-hostkey-" + container + "\n"}
				case cmd == "systemctl" && len(args) > 3 && args[3] == "enable":
					return docker.MockResult{}
				case cmd == "systemctl" && len(args) > 3 && args[3] == "is-active":
					return docker.MockResult{Stdout: "active\n"}
				}
			}
			return docker.MockResult{}

		// DNS record operations (CopyFromContainer, CopyToContainer, kill)
		case args[0] == "cp":
			if len(args) == 3 && args[2] == "-" && strings.Contains(args[1], "sind-dns") {
				return docker.MockResult{Stdout: emptyCorefileTar()}
			}
			return docker.MockResult{}

		case args[0] == "kill":
			return docker.MockResult{}

		// RemoveContainer (helper cleanup)
		case args[0] == "rm":
			return docker.MockResult{}
		}

		t.Logf("unhandled worker mock call: %v", args)
		return docker.MockResult{}
	}
}

func TestWorkerAdd_Managed(t *testing.T) {
	var m docker.MockExecutor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        4,
		Memory:      "8g",
		TmpSize:     "1g",
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 1)
	assert.Equal(t, "compute-1", nodes[0].Name)
	assert.Equal(t, "compute", nodes[0].Role)
	assert.Equal(t, StatusRunning, nodes[0].Status)

	// Verify key docker calls were made.
	var createArgs, scontrolCalled, slurmdEnabled bool
	var writeStdin string
	for _, call := range m.Calls {
		args := call.Args
		joined := strings.Join(args, " ")
		// Container created with correct name
		if args[0] == "create" && strings.Contains(joined, "sind-dev-compute-1") {
			createArgs = true
		}
		// sind-nodes.conf updated (WriteFile via exec -i on controller)
		if args[0] == "exec" && args[1] == "-i" && strings.Contains(joined, "sind-dev-controller") {
			writeStdin = call.Stdin
		}
		// scontrol reconfigure called
		if args[0] == "exec" && len(args) > 2 && args[1] == "sind-dev-controller" && args[2] == "scontrol" {
			scontrolCalled = true
		}
		// slurmd enabled on new node
		if args[0] == "exec" && len(args) > 3 && strings.Contains(args[1], "compute-1") && args[2] == "systemctl" && args[3] == "enable" {
			slurmdEnabled = true
		}
	}

	assert.True(t, createArgs, "compute-1 container should be created")
	assert.True(t, scontrolCalled, "scontrol reconfigure should be called")
	assert.True(t, slurmdEnabled, "slurmd should be enabled on new node")
	assert.Contains(t, writeStdin, "compute-1", "sind-nodes.conf should include compute-1")
}

func TestWorkerAdd_Managed_UsesControllerImage(t *testing.T) {
	// When no image is specified, WorkerAdd uses the controller's image.
	var m docker.MockExecutor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
		// Image intentionally omitted → should use controller image "img:1"
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 1)

	// Verify the create call used the controller's image.
	for _, call := range m.Calls {
		if call.Args[0] == "create" {
			assert.Contains(t, call.Args, "img:1", "should use controller image when none specified")
			break
		}
	}
}

func TestWorkerAdd_Managed_ControllerNotFound(t *testing.T) {
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ""}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client)

	_, err := WorkerAdd(context.Background(), client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
	}, time.Millisecond)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "controller not found")
}

// --- WorkerAdd (unmanaged) ---

func TestWorkerAdd_Unmanaged(t *testing.T) {
	var m docker.MockExecutor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
		Unmanaged:   true,
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 1)
	assert.Equal(t, "compute-1", nodes[0].Name)
	assert.Equal(t, "compute", nodes[0].Role)
	assert.Equal(t, StatusRunning, nodes[0].Status)

	// Verify slurm config was NOT updated and slurmd was NOT enabled.
	for _, call := range m.Calls {
		args := call.Args
		joined := strings.Join(args, " ")
		// Should not read/write sind-nodes.conf on controller
		if args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "cat" &&
			strings.Contains(joined, "sind-nodes.conf") {
			t.Error("should not read sind-nodes.conf for unmanaged worker")
		}
		// Should not call scontrol reconfigure
		if args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "scontrol" {
			t.Error("should not call scontrol reconfigure for unmanaged worker")
		}
		// Should not enable slurmd on new node
		if args[0] == "exec" && len(args) > 3 && strings.Contains(args[1], "compute-1") &&
			args[2] == "systemctl" && args[3] == "enable" {
			t.Error("should not enable slurmd for unmanaged worker")
		}
	}
}
