// SPDX-License-Identifier: LGPL-3.0-or-later

package cluster

import (
	"context"
	"fmt"
	"testing"

	"github.com/GSI-HPC/sind/pkg/docker"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// --- ValidateWorkerAdd ---

func TestWorkerAdd_RequiresSindNodes(t *testing.T) {
	// When sind-nodes.conf is missing on the controller,
	// managed worker add must fail.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		// ListContainers: controller exists
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ndjson(
				psEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
			)}
		}
		// ReadFile (docker exec controller cat /etc/slurm/sind-nodes.conf) fails
		if args[0] == "exec" && len(args) >= 4 && args[2] == "cat" {
			return docker.MockResult{Err: fmt.Errorf("cat: /etc/slurm/sind-nodes.conf: No such file or directory")}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "sind-nodes.conf")
}

func TestWorkerAdd_RequiresSindNodes_Present(t *testing.T) {
	// When sind-nodes.conf exists, validation passes for managed workers.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ndjson(
				psEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
			)}
		}
		if args[0] == "exec" && len(args) >= 4 && args[2] == "cat" {
			return docker.MockResult{Stdout: "# Generated by sind\nNodeName=compute-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n"}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.NoError(t, err)
}

func TestWorkerAdd_AllowsUnmanaged(t *testing.T) {
	// Unmanaged worker add bypasses sind-nodes.conf check.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ndjson(
				psEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
			)}
		}
		// Should never reach ReadFile for unmanaged
		if args[0] == "exec" {
			return docker.MockResult{Err: fmt.Errorf("should not be called")}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		Unmanaged:   true,
	})

	require.NoError(t, err)
}

func TestWorkerAdd_ClusterNotFound(t *testing.T) {
	// If no controller container exists for the cluster, validation fails.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ""}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "controller not found")
}

func TestWorkerAdd_ClusterNotFound_Unmanaged(t *testing.T) {
	// Even unmanaged mode requires the cluster (controller) to exist.
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Stdout: ""}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		Unmanaged:   true,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "controller not found")
}

func TestWorkerAdd_ListContainersError(t *testing.T) {
	var m docker.MockExecutor
	m.OnCall = func(args []string, _ string) docker.MockResult {
		if args[0] == "ps" {
			return docker.MockResult{Err: fmt.Errorf("docker daemon not running")}
		}
		return docker.MockResult{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(context.Background(), client, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "listing cluster containers")
}
