// SPDX-License-Identifier: LGPL-3.0-or-later

package cluster

import (
	"context"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/GSI-HPC/sind/internal/mock"
	"github.com/GSI-HPC/sind/internal/testutil"
	"github.com/GSI-HPC/sind/pkg/config"
	"github.com/GSI-HPC/sind/pkg/docker"
	"github.com/GSI-HPC/sind/pkg/mesh"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// workerContainers returns a standard set of cluster containers for worker tests.
func workerContainers(computes ...string) string {
	entries := []testutil.PsEntry{
		{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
			Labels: "sind.cluster=dev,sind.role=controller"},
	}
	for _, c := range computes {
		entries = append(entries, testutil.PsEntry{
			ID: "c" + c, Names: "sind-dev-" + c, State: "running", Image: "img:1",
			Labels: "sind.cluster=dev,sind.role=worker",
		})
	}
	return testutil.NDJSON(entries...)
}

// --- ValidateWorkerAdd ---

func TestWorkerAdd_RequiresSindNodes(t *testing.T) {
	// When sind-nodes.conf is missing on the controller,
	// managed worker add must fail.
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		// ListContainers: controller exists
		if args[0] == "ps" {
			return mock.Result{Stdout: testutil.NDJSON(
				testutil.PsEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
			)}
		}
		// ReadFile (docker exec controller cat /etc/slurm/sind-nodes.conf) fails
		if args[0] == "exec" && len(args) >= 4 && args[2] == "cat" {
			return mock.Result{Err: fmt.Errorf("cat: /etc/slurm/sind-nodes.conf: No such file or directory")}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(t.Context(), client, mesh.DefaultRealm, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "sind-nodes.conf")
}

func TestWorkerAdd_RequiresSindNodes_Present(t *testing.T) {
	// When sind-nodes.conf exists, validation passes for managed workers.
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: testutil.NDJSON(
				testutil.PsEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
			)}
		}
		if args[0] == "exec" && len(args) >= 4 && args[2] == "cat" {
			return mock.Result{Stdout: "# Generated by sind\nNodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n"}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(t.Context(), client, mesh.DefaultRealm, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.NoError(t, err)
}

func TestWorkerAdd_AllowsUnmanaged(t *testing.T) {
	// Unmanaged worker add bypasses sind-nodes.conf check.
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: testutil.NDJSON(
				testutil.PsEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
			)}
		}
		// Should never reach ReadFile for unmanaged
		if args[0] == "exec" {
			return mock.Result{Err: fmt.Errorf("should not be called")}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(t.Context(), client, mesh.DefaultRealm, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		Unmanaged:   true,
	})

	require.NoError(t, err)
}

func TestWorkerAdd_ClusterNotFound(t *testing.T) {
	// If no controller container exists for the cluster, validation fails.
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: ""}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(t.Context(), client, mesh.DefaultRealm, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "controller not found")
}

func TestWorkerAdd_ClusterNotFound_Unmanaged(t *testing.T) {
	// Even unmanaged mode requires the cluster (controller) to exist.
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: ""}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(t.Context(), client, mesh.DefaultRealm, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		Unmanaged:   true,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "controller not found")
}

func TestWorkerAdd_ListContainersError(t *testing.T) {
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Err: fmt.Errorf("docker daemon not running")}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	err := ValidateWorkerAdd(t.Context(), client, mesh.DefaultRealm, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "listing containers")
}

// --- NextComputeIndex ---

func TestNextComputeIndex_Empty(t *testing.T) {
	// No worker containers → next index is 0.
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: testutil.NDJSON(
				testutil.PsEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
			)}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	idx, err := NextComputeIndex(t.Context(), client, mesh.DefaultRealm, "dev")

	require.NoError(t, err)
	assert.Equal(t, 0, idx)
}

func TestNextComputeIndex_Sequential(t *testing.T) {
	// worker-0 and worker-1 exist → next index is 2.
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: workerContainers("worker-0", "worker-1")}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	idx, err := NextComputeIndex(t.Context(), client, mesh.DefaultRealm, "dev")

	require.NoError(t, err)
	assert.Equal(t, 2, idx)
}

func TestNextComputeIndex_Gap(t *testing.T) {
	// worker-0 and worker-3 exist → next index is 4 (fills after max).
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: workerContainers("worker-0", "worker-3")}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	idx, err := NextComputeIndex(t.Context(), client, mesh.DefaultRealm, "dev")

	require.NoError(t, err)
	assert.Equal(t, 4, idx)
}

func TestNextComputeIndex_NonComputeIgnored(t *testing.T) {
	// Controller and submitter don't affect worker index.
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: testutil.NDJSON(
				testutil.PsEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
				testutil.PsEntry{ID: "def", Names: "sind-dev-submitter", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=submitter"},
			)}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	idx, err := NextComputeIndex(t.Context(), client, mesh.DefaultRealm, "dev")

	require.NoError(t, err)
	assert.Equal(t, 0, idx)
}

func TestNextComputeIndex_ListError(t *testing.T) {
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Err: fmt.Errorf("docker daemon not running")}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	_, err := NextComputeIndex(t.Context(), client, mesh.DefaultRealm, "dev")

	require.Error(t, err)
	assert.Contains(t, err.Error(), "listing containers")
}

// --- WorkerAdd (managed) ---

// workerAddOnCall returns a mock OnCall handler for the WorkerAdd managed flow.
// The cluster has 1 controller + 1 existing worker (worker-0).
// The new worker will be worker-1.
func workerAddOnCall(t *testing.T) func([]string, string) mock.Result {
	t.Helper()

	nodesConf := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n"

	return func(args []string, _ string) mock.Result {
		if len(args) == 0 {
			return mock.Result{}
		}
		joined := strings.Join(args, " ")

		switch {
		// ListContainers: cluster has controller + worker-0
		case args[0] == "ps":
			return mock.Result{Stdout: workerContainers("worker-0")}

		// InspectContainer: sind-dns → return mesh IP
		case args[0] == "inspect" && args[1] == "sind-dns":
			return mock.Result{Stdout: inspectJSON(t, "sind-dns", "running", map[docker.NetworkName]string{
				"sind-mesh": "10.0.0.2",
			})}

		// InspectContainer: controller → return slurm version label
		case args[0] == "inspect" && args[1] == "sind-dev-controller":
			return mock.Result{Stdout: inspectJSONLabels(t, "sind-dev-controller", "running",
				map[docker.NetworkName]string{"sind-dev-net": "10.0.1.1"},
				docker.Labels{"sind.slurm.version": "25.11.0"})}

		// InspectContainer: new worker node
		case args[0] == "inspect" && strings.HasPrefix(args[1], "sind-dev-worker-"):
			return mock.Result{Stdout: inspectJSON(t, args[1], "running", map[docker.NetworkName]string{
				"sind-dev-net": "10.0.1.3",
			})}

		// ReadFile: SSH pubkey from sind-ssh
		case args[0] == "exec" && args[1] == "sind-ssh" && len(args) > 2 && args[2] == "cat":
			return mock.Result{Stdout: "ssh-ed25519 AAAA-test-key\n"}

		// ReadFile: sind-nodes.conf (for validation and update)
		case args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "cat":
			return mock.Result{Stdout: nodesConf}

		// WriteFile: updated sind-nodes.conf
		case args[0] == "exec" && args[1] == "-i" && strings.Contains(joined, "sind-dev-controller"):
			return mock.Result{}

		// scontrol reconfigure
		case args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "scontrol":
			return mock.Result{}

		// CreateContainer
		case args[0] == "create":
			return mock.Result{Stdout: "new-cid\n"}

		// ConnectNetwork (mesh)
		case args[0] == "network" && args[1] == "connect":
			return mock.Result{}

		// StartContainer
		case args[0] == "start":
			return mock.Result{}

		// Exec on new worker: probes, SSH inject, host key, systemctl
		case args[0] == "exec":
			container := args[1]
			if container == "-i" {
				// ExecWithStdin (SSH key inject, WriteFile)
				return mock.Result{}
			}
			if len(args) > 2 {
				switch cmd := args[2]; {
				case cmd == "sh" && strings.Contains(joined, "is-system-running"):
					return mock.Result{Stdout: "running\n"}
				case cmd == "bash" && strings.Contains(joined, "/dev/tcp"):
					return mock.Result{Stdout: "SSH-2.0-OpenSSH_9.0\n"}
				case cmd == "mkdir":
					return mock.Result{}
				case cmd == "ssh-keyscan":
					return mock.Result{Stdout: "localhost ssh-ed25519 AAAA-hostkey-" + container + "\n"}
				case cmd == "systemctl" && len(args) > 3 && args[3] == "enable":
					return mock.Result{}
				case cmd == "systemctl" && len(args) > 3 && args[3] == "is-active":
					return mock.Result{Stdout: "active\n"}
				}
			}
			return mock.Result{}

		// DNS record operations (CopyFromContainer, CopyToContainer, kill)
		case args[0] == "cp":
			if len(args) == 3 && args[2] == "-" && strings.Contains(args[1], "sind-dns") {
				return mock.Result{Stdout: emptyCorefileTar()}
			}
			return mock.Result{}

		case args[0] == "kill":
			return mock.Result{}

		// RemoveContainer (helper cleanup or worker cleanup)
		case args[0] == "rm":
			return mock.Result{}
		}

		t.Logf("unhandled worker mock call: %v", args)
		return mock.Result{}
	}
}

func TestWorkerAdd_Managed(t *testing.T) {
	pipes := &mock.Pipes{}
	defer pipes.CloseAll()

	var m mock.Executor
	m.OnCall = workerAddOnCall(t)
	m.OnStart = pipes.OnStart
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        4,
		Memory:      "8g",
		TmpSize:     "1g",
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 1)
	assert.Equal(t, "worker-1", nodes[0].Name)
	assert.Equal(t, config.RoleWorker, nodes[0].Role)
	assert.Equal(t, StateRunning, nodes[0].State)

	// Verify key docker calls were made.
	var createArgs, scontrolCalled, slurmdEnabled bool
	var writeStdin string
	for _, call := range m.Calls {
		args := call.Args
		joined := strings.Join(args, " ")
		// Container created with correct name
		if args[0] == "create" && strings.Contains(joined, "sind-dev-worker-1") {
			createArgs = true
		}
		// sind-nodes.conf updated (WriteFile via exec -i on controller)
		if args[0] == "exec" && args[1] == "-i" && strings.Contains(joined, "sind-dev-controller") {
			writeStdin = call.Stdin
		}
		// scontrol reconfigure called
		if args[0] == "exec" && len(args) > 2 && args[1] == "sind-dev-controller" && args[2] == "scontrol" {
			scontrolCalled = true
		}
		// slurmd enabled on new node
		if args[0] == "exec" && len(args) > 3 && strings.Contains(args[1], "worker-1") && args[2] == "systemctl" && args[3] == "enable" {
			slurmdEnabled = true
		}
	}

	assert.True(t, createArgs, "worker-1 container should be created")
	assert.True(t, scontrolCalled, "scontrol reconfigure should be called")
	assert.True(t, slurmdEnabled, "slurmd should be enabled on new node")
	assert.Contains(t, writeStdin, "worker-1", "sind-nodes.conf should include worker-1")
}

func TestWorkerAdd_Managed_UsesControllerImage(t *testing.T) {
	// When no image is specified, WorkerAdd uses the controller's image.
	var m mock.Executor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
		// Image intentionally omitted → should use controller image "img:1"
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 1)

	// Verify the create call used the controller's image.
	for _, call := range m.Calls {
		if call.Args[0] == "create" {
			assert.Contains(t, call.Args, "img:1", "should use controller image when none specified")
			break
		}
	}
}

func TestWorkerAdd_Managed_ControllerNotFound(t *testing.T) {
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: ""}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	_, err := WorkerAdd(t.Context(), client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
	}, time.Millisecond)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "controller not found")
}

// --- WorkerAdd (unmanaged) ---

func TestWorkerAdd_Unmanaged(t *testing.T) {
	var m mock.Executor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
		Unmanaged:   true,
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 1)
	assert.Equal(t, "worker-1", nodes[0].Name)
	assert.Equal(t, config.RoleWorker, nodes[0].Role)
	assert.Equal(t, StateRunning, nodes[0].State)

	// Verify slurm config was NOT updated and slurmd was NOT enabled.
	for _, call := range m.Calls {
		args := call.Args
		joined := strings.Join(args, " ")
		// Should not read/write sind-nodes.conf on controller
		if args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "cat" &&
			strings.Contains(joined, "sind-nodes.conf") {
			assert.Fail(t, "should not read sind-nodes.conf for unmanaged worker")
		}
		// Should not call scontrol reconfigure
		if args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "scontrol" {
			assert.Fail(t, "should not call scontrol reconfigure for unmanaged worker")
		}
		// Should not enable slurmd on new node
		if args[0] == "exec" && len(args) > 3 && strings.Contains(args[1], "worker-1") &&
			args[2] == "systemctl" && args[3] == "enable" {
			assert.Fail(t, "should not enable slurmd for unmanaged worker")
		}
	}
}

// --- WorkerRemove (managed) ---

// workerRemoveOnCall returns a mock OnCall handler for WorkerRemove tests.
// The cluster has controller + worker-0 + worker-1, removing worker-1.
func workerRemoveOnCall(t *testing.T, nodesConf string) func([]string, string) mock.Result {
	t.Helper()

	return func(args []string, _ string) mock.Result {
		if len(args) == 0 {
			return mock.Result{}
		}
		joined := strings.Join(args, " ")

		switch {
		// ListContainers
		case args[0] == "ps":
			return mock.Result{Stdout: workerContainers("worker-0", "worker-1")}

		// ReadFile: sind-nodes.conf
		case args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "cat":
			if nodesConf == "" {
				return mock.Result{Err: fmt.Errorf("No such file")}
			}
			return mock.Result{Stdout: nodesConf}

		// WriteFile: updated sind-nodes.conf
		case args[0] == "exec" && args[1] == "-i" && strings.Contains(joined, "sind-dev-controller"):
			return mock.Result{}

		// scontrol reconfigure
		case args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "scontrol":
			return mock.Result{}

		// DNS: CopyFromContainer (read Corefile)
		case args[0] == "cp" && len(args) == 3 && args[2] == "-" && strings.Contains(args[1], "sind-dns"):
			return mock.Result{Stdout: emptyCorefileTar()}

		// DNS: CopyToContainer / signal
		case args[0] == "cp":
			return mock.Result{}
		case args[0] == "kill":
			return mock.Result{}

		// Known hosts: exec on sind-ssh
		case args[0] == "exec" && args[1] == "sind-ssh":
			return mock.Result{Stdout: "worker-1.dev.sind.sind ssh-ed25519 AAAA\n"}
		case args[0] == "exec" && args[1] == "-i":
			return mock.Result{}

		// Start (DNS reload after kill)
		case args[0] == "start":
			return mock.Result{}

		// RemoveContainer (rm -f)
		case args[0] == "rm":
			return mock.Result{}
		}

		t.Logf("unhandled worker remove mock call: %v", args)
		return mock.Result{}
	}
}

func TestWorkerRemove_Managed(t *testing.T) {
	nodesConf := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-1 Default=YES MaxTime=INFINITE State=UP\n"

	var m mock.Executor
	m.OnCall = workerRemoveOnCall(t, nodesConf)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", []string{"worker-1"})

	require.NoError(t, err)

	// Verify key operations.
	var scontrolCalled, containerRemoved bool
	var writeStdin string
	for _, call := range m.Calls {
		args := call.Args
		joined := strings.Join(args, " ")
		if args[0] == "exec" && args[1] == "-i" && strings.Contains(joined, "sind-dev-controller") {
			writeStdin = call.Stdin
		}
		if args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "scontrol" {
			scontrolCalled = true
		}
		if args[0] == "rm" && strings.Contains(joined, "worker-1") {
			containerRemoved = true
		}
	}

	assert.True(t, scontrolCalled, "scontrol reconfigure should be called")
	assert.True(t, containerRemoved, "container should be removed")
	assert.Contains(t, writeStdin, "worker-0", "updated conf should still have worker-0")
	assert.NotContains(t, writeStdin, "worker-1", "updated conf should not have worker-1")
}

func TestWorkerRemove_NodeNotFound(t *testing.T) {
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: workerContainers("worker-0")}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", []string{"worker-99"})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "not found")
}

// --- WorkerRemove (unmanaged) ---

func TestWorkerRemove_Unmanaged(t *testing.T) {
	// sind-nodes.conf missing → treat as unmanaged (no slurm config update).
	var m mock.Executor
	m.OnCall = workerRemoveOnCall(t, "") // empty nodesConf → ReadFile fails
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", []string{"worker-1"})

	require.NoError(t, err)

	// Verify no scontrol reconfigure was called.
	for _, call := range m.Calls {
		args := call.Args
		if args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "scontrol" {
			assert.Fail(t, "should not call scontrol reconfigure for unmanaged removal")
		}
	}

	// Verify container was removed (rm -f handles kill internally).
	var removed bool
	for _, call := range m.Calls {
		joined := strings.Join(call.Args, " ")
		if call.Args[0] == "rm" && strings.Contains(joined, "worker-1") {
			removed = true
		}
	}
	assert.True(t, removed, "container should be removed")
}

// --- Additional test combinatorics ---

func TestWorkerAdd_MultipleNodes(t *testing.T) {
	var m mock.Executor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       2,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 2)
	assert.Equal(t, "worker-1", nodes[0].Name)
	assert.Equal(t, "worker-2", nodes[1].Name)

	// Verify both nodes appear in sind-nodes.conf update.
	for _, call := range m.Calls {
		if call.Args[0] == "exec" && call.Args[1] == "-i" &&
			strings.Contains(strings.Join(call.Args, " "), "sind-dev-controller") {
			assert.Contains(t, call.Stdin, "worker-1")
			assert.Contains(t, call.Stdin, "worker-2")
			break
		}
	}
}

func TestWorkerAdd_ExplicitImage(t *testing.T) {
	var m mock.Executor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	_, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		Image:       "custom:v1",
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
	}, time.Millisecond)

	require.NoError(t, err)

	for _, call := range m.Calls {
		if call.Args[0] == "create" {
			assert.Contains(t, call.Args, "custom:v1", "should use explicit image")
			assert.NotContains(t, call.Args, "img:1", "should not use controller image")
			break
		}
	}
}

func TestWorkerAdd_InfraError(t *testing.T) {
	var m mock.Executor
	inner := workerAddOnCall(t)
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "inspect" && args[1] == "sind-dns" {
			return mock.Result{Err: fmt.Errorf("DNS container not running")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	_, err := WorkerAdd(t.Context(), client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
	}, time.Millisecond)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "inspecting DNS container")
}

func TestWorkerAdd_SindNodesConfMissing(t *testing.T) {
	var m mock.Executor
	inner := workerAddOnCall(t)
	m.OnCall = func(args []string, stdin string) mock.Result {
		// Make ReadFile for sind-nodes.conf fail
		if args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "cat" {
			return mock.Result{Err: fmt.Errorf("No such file")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	_, err := WorkerAdd(t.Context(), client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
	}, time.Millisecond)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "sind-nodes.conf")
}

func TestWorkerAdd_InvalidMemory(t *testing.T) {
	// When Memory is invalid, WorkerAdd should return a parse error
	// instead of silently defaulting to 0.
	var m mock.Executor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	_, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        2,
		Memory:      "bogus",
		TmpSize:     "1g",
	}, time.Millisecond)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "parsing memory")
}

func TestWorkerRemove_MultipleNodes(t *testing.T) {
	nodesConf := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-1 Default=YES MaxTime=INFINITE State=UP\n"

	var m mock.Executor
	m.OnCall = workerRemoveOnCall(t, nodesConf)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", []string{"worker-0", "worker-1"})

	require.NoError(t, err)

	// Verify both worker containers were removed (rm -f handles kill internally).
	var removeCount int
	for _, call := range m.Calls {
		if call.Args[0] == "rm" && len(call.Args) >= 2 && strings.HasPrefix(call.Args[len(call.Args)-1], "sind-dev-worker-") {
			removeCount++
		}
	}
	assert.Equal(t, 2, removeCount, "both containers should be removed")
}

func TestWorkerRemove_ListContainersError(t *testing.T) {
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Err: fmt.Errorf("docker daemon not running")}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", []string{"worker-0"})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "listing containers")
}

func TestWorkerAdd_DefaultCount(t *testing.T) {
	// When Count is 0 (zero value), WorkerAdd defaults to creating 1 node.
	var m mock.Executor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		// Count intentionally 0 → should default to 1
		CPUs:    2,
		Memory:  "2g",
		TmpSize: "1g",
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 1)
	assert.Equal(t, "worker-1", nodes[0].Name)
}

func TestWorkerAdd_DefaultResources(t *testing.T) {
	// When CPUs, Memory, TmpSize are zero/empty, WorkerAdd defaults to
	// config.DefaultCPUs, config.DefaultMemory, config.DefaultTmpSize.
	var m mock.Executor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		// CPUs, Memory, TmpSize intentionally omitted → should use defaults
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 1)
}

func TestWorkerAdd_Unmanaged_MultipleNodes(t *testing.T) {
	var m mock.Executor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       2,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
		Unmanaged:   true,
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 2)
	assert.Equal(t, "worker-1", nodes[0].Name)
	assert.Equal(t, "worker-2", nodes[1].Name)

	// Verify no slurm operations were performed.
	for _, call := range m.Calls {
		args := call.Args
		if args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "scontrol" {
			assert.Fail(t, "should not call scontrol reconfigure for unmanaged workers")
		}
	}
}

func TestWorkerRemove_NoController(t *testing.T) {
	// When the controller is already gone (orphaned workers), removal should
	// skip slurm config update and still delete the containers.
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if len(args) == 0 {
			return mock.Result{}
		}
		switch {
		case args[0] == "ps":
			// Only worker nodes, no controller.
			return mock.Result{Stdout: testutil.NDJSON(
				testutil.PsEntry{ID: "c0", Names: "sind-dev-worker-0", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=worker"},
			)}
		case args[0] == "cp" && len(args) == 3 && args[2] == "-" && strings.Contains(args[1], "sind-dns"):
			return mock.Result{Stdout: emptyCorefileTar()}
		case args[0] == "cp":
			return mock.Result{}
		case args[0] == "kill":
			return mock.Result{}
		case args[0] == "exec" && args[1] == "sind-ssh":
			return mock.Result{Stdout: "worker-0.dev.sind.sind ssh-ed25519 AAAA\n"}
		case args[0] == "exec" && args[1] == "-i":
			return mock.Result{}
		case args[0] == "rm":
			return mock.Result{}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", []string{"worker-0"})

	require.NoError(t, err)

	// Verify no slurm config operations were attempted.
	for _, call := range m.Calls {
		args := call.Args
		if args[0] == "exec" && len(args) > 1 && args[1] == "sind-dev-controller" {
			assert.Fail(t, "should not interact with controller when it doesn't exist")
		}
	}

	// Verify container was still removed.
	var removed bool
	for _, call := range m.Calls {
		if call.Args[0] == "rm" && strings.Contains(strings.Join(call.Args, " "), "worker-0") {
			removed = true
		}
	}
	assert.True(t, removed, "container should be removed even without controller")
}

func TestNextComputeIndex_NonNumericSuffix(t *testing.T) {
	// Containers with non-numeric suffixes (e.g. worker-abc) are ignored.
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: testutil.NDJSON(
				testutil.PsEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
				testutil.PsEntry{ID: "c0", Names: "sind-dev-worker-0", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=worker"},
				testutil.PsEntry{ID: "cx", Names: "sind-dev-worker-abc", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=worker"},
			)}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)

	idx, err := NextComputeIndex(t.Context(), client, mesh.DefaultRealm, "dev")

	require.NoError(t, err)
	assert.Equal(t, 1, idx)
}

func TestWorkerRemove_RejectsController(t *testing.T) {
	// Removing the controller via worker remove must be rejected.
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: workerContainers("worker-0")}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", []string{"controller"})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "only worker nodes")
}

func TestWorkerRemove_RejectsSubmitter(t *testing.T) {
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Stdout: testutil.NDJSON(
				testutil.PsEntry{ID: "abc", Names: "sind-dev-controller", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=controller"},
				testutil.PsEntry{ID: "sub", Names: "sind-dev-submitter", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=submitter"},
				testutil.PsEntry{ID: "c0", Names: "sind-dev-worker-0", State: "running", Image: "img:1",
					Labels: "sind.cluster=dev,sind.role=worker"},
			)}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", []string{"submitter"})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "only worker nodes")
}

func TestWorkerRemove_DuplicateNames(t *testing.T) {
	// Duplicate names should be deduplicated — container removed only once.
	var m mock.Executor
	m.OnCall = workerRemoveOnCall(t, "")
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", []string{"worker-1", "worker-1"})

	require.NoError(t, err)

	var removeCount int
	for _, call := range m.Calls {
		if call.Args[0] == "rm" && strings.Contains(strings.Join(call.Args, " "), "worker-1") {
			removeCount++
		}
	}
	assert.Equal(t, 1, removeCount, "container should be removed exactly once")
}

func TestWorkerRemove_EmptyNames(t *testing.T) {
	// Empty shortNames is a no-op — no docker calls should be made.
	var m mock.Executor
	m.OnCall = func(_ []string, _ string) mock.Result {
		return mock.Result{Err: fmt.Errorf("should not be called")}
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", nil)

	require.NoError(t, err)
	assert.Empty(t, m.Calls, "no docker calls should be made for empty shortNames")
}

func TestWorkerAdd_NegativeCount(t *testing.T) {
	// Negative count defaults to 1, same as zero.
	var m mock.Executor
	m.OnCall = workerAddOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       -5,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 1)
	assert.Equal(t, "worker-1", nodes[0].Name)
}

// --- WorkerAdd error path tests ---

func TestWorkerAdd_ListError(t *testing.T) {
	var m mock.Executor
	m.OnCall = func(args []string, _ string) mock.Result {
		if args[0] == "ps" {
			return mock.Result{Err: fmt.Errorf("docker daemon not running")}
		}
		return mock.Result{}
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	_, err := WorkerAdd(t.Context(), client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, time.Millisecond)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "listing containers")
}

func TestWorkerAdd_CreateNodeError(t *testing.T) {
	var m mock.Executor
	inner := workerAddOnCall(t)
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "create" {
			return mock.Result{Err: fmt.Errorf("image not found")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	_, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, time.Millisecond)

	require.Error(t, err)
}

func TestWorkerAdd_SetupNodesError(t *testing.T) {
	var m mock.Executor
	inner := workerAddOnCall(t)
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "exec" && len(args) > 2 && args[2] == "sh" &&
			strings.Contains(strings.Join(args, " "), "is-system-running") {
			return mock.Result{Err: fmt.Errorf("container not running")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 200*time.Millisecond)
	defer cancel()

	_, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, 50*time.Millisecond)

	require.Error(t, err)
}

func TestWorkerAdd_RegisterNodesError(t *testing.T) {
	var m mock.Executor
	inner := workerAddOnCall(t)
	m.OnCall = func(args []string, stdin string) mock.Result {
		// Fail on DNS CopyFromContainer (cp ... sind-dns:... -)
		if args[0] == "cp" && len(args) == 3 && args[2] == "-" && strings.Contains(args[1], "sind-dns") {
			return mock.Result{Err: fmt.Errorf("DNS container crashed")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	_, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, time.Millisecond)

	require.Error(t, err)
}

func TestWorkerAdd_EnableSlurmError(t *testing.T) {
	var m mock.Executor
	inner := workerAddOnCall(t)
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "exec" && len(args) > 3 &&
			strings.Contains(args[1], "worker") && args[2] == "systemctl" && args[3] == "enable" {
			return mock.Result{Err: fmt.Errorf("systemctl failed")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	_, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, time.Millisecond)

	require.Error(t, err)
}

func TestWorkerAdd_CleansUpOnFailure(t *testing.T) {
	// When enableSlurm fails (after containers exist), cleanup should run.
	var m mock.Executor
	inner := workerAddOnCall(t)
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "exec" && len(args) > 3 &&
			strings.Contains(args[1], "worker") && args[2] == "systemctl" && args[3] == "enable" {
			return mock.Result{Err: fmt.Errorf("systemctl failed")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	_, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, time.Millisecond)

	require.Error(t, err)
	// Verify cleanup ran: look for "docker rm -f" on the new worker container.
	var removed bool
	for _, call := range m.Calls {
		if call.Args[0] == "rm" && len(call.Args) >= 2 && strings.HasPrefix(call.Args[len(call.Args)-1], "sind-dev-worker-") {
			removed = true
		}
	}
	assert.True(t, removed, "cleanup should remove the new worker container")
}

func TestWorkerAdd_CleanupErrors(t *testing.T) {
	// When cleanup itself encounters errors (RemoveKnownHost, RemoveContainer),
	// those errors are logged but do not mask the original failure.
	var m mock.Executor
	inner := workerAddOnCall(t)
	inCleanup := false
	m.OnCall = func(args []string, stdin string) mock.Result {
		// Make enableSlurm fail to trigger cleanup.
		if args[0] == "exec" && len(args) > 3 &&
			strings.Contains(args[1], "worker") && args[2] == "systemctl" && args[3] == "enable" {
			inCleanup = true
			return mock.Result{Err: fmt.Errorf("systemctl failed")}
		}
		if !inCleanup {
			return inner(args, stdin)
		}
		// During cleanup: make RemoveKnownHost and RemoveContainer fail.
		if args[0] == "exec" && args[1] == "-i" {
			return mock.Result{Err: fmt.Errorf("write failed")}
		}
		if args[0] == "rm" {
			return mock.Result{Err: fmt.Errorf("container locked")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	_, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, time.Millisecond)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "systemctl failed")
}

func TestWorkerAdd_NoCleanupOnValidationFailure(t *testing.T) {
	// When validation fails (before containers), cleanup should NOT run.
	var m mock.Executor
	inner := workerAddOnCall(t)
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "inspect" && args[1] == "sind-dev-controller" {
			return mock.Result{Err: fmt.Errorf("container not running")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	_, err := WorkerAdd(t.Context(), client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, time.Millisecond)

	require.Error(t, err)
	// No "docker rm" calls on worker containers → cleanup did not run.
	for _, call := range m.Calls {
		if call.Args[0] == "rm" && len(call.Args) >= 2 && strings.HasPrefix(call.Args[len(call.Args)-1], "sind-dev-worker-") {
			require.Fail(t, "cleanup should not run when validation fails")
		}
	}
}

func TestWorkerAdd_ControllerInspectError(t *testing.T) {
	var m mock.Executor
	inner := workerAddOnCall(t)
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "inspect" && args[1] == "sind-dev-controller" {
			return mock.Result{Err: fmt.Errorf("container not running")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	_, err := WorkerAdd(t.Context(), client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, time.Millisecond)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "inspecting controller")
}

func TestWorkerAdd_UpdateNodesConfReadError(t *testing.T) {
	// The first sind-nodes.conf read (validation) succeeds,
	// but the second read (inside updateNodesConf) fails.
	var m mock.Executor
	inner := workerAddOnCall(t)
	readCount := 0
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "cat" &&
			strings.Contains(strings.Join(args, " "), "sind-nodes.conf") {
			readCount++
			if readCount >= 2 {
				return mock.Result{Err: fmt.Errorf("file disappeared")}
			}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	_, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, time.Millisecond)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "reading sind-nodes.conf")
}

func TestWorkerAdd_WriteNodesConfError(t *testing.T) {
	var m mock.Executor
	inner := workerAddOnCall(t)
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "exec" && args[1] == "-i" &&
			strings.Contains(strings.Join(args, " "), "sind-dev-controller") {
			return mock.Result{Err: fmt.Errorf("disk full")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	_, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, time.Millisecond)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "updating sind-nodes.conf")
}

func TestWorkerAdd_ScontrolReconfigureError(t *testing.T) {
	var m mock.Executor
	inner := workerAddOnCall(t)
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "scontrol" {
			return mock.Result{Err: fmt.Errorf("slurmctld not responding")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	_, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev", Count: 1, CPUs: 2, Memory: "2g", TmpSize: "1g",
	}, time.Millisecond)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "reconfiguring slurmctld")
}

// --- WorkerRemove error path tests ---

func TestWorkerRemove_RemoveNodesConfError(t *testing.T) {
	nodesConf := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"NodeName=worker-1 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0,worker-1 Default=YES MaxTime=INFINITE State=UP\n"

	var m mock.Executor
	inner := workerRemoveOnCall(t, nodesConf)
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "exec" && args[1] == "-i" &&
			strings.Contains(strings.Join(args, " "), "sind-dev-controller") {
			return mock.Result{Err: fmt.Errorf("disk full")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", []string{"worker-1"})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "updating sind-nodes.conf")
}

func TestWorkerRemove_DeregisterMeshError(t *testing.T) {
	var m mock.Executor
	inner := workerRemoveOnCall(t, "")
	m.OnCall = func(args []string, stdin string) mock.Result {
		if args[0] == "cp" && len(args) == 3 && args[2] == "-" && strings.Contains(args[1], "sind-dns") {
			return mock.Result{Err: fmt.Errorf("DNS container crashed")}
		}
		return inner(args, stdin)
	}
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	err := WorkerRemove(t.Context(), client, mgr, "dev", []string{"worker-1"})

	require.Error(t, err)
}

// --- Lifecycle ---

// workerLifecycleOnCall handles both add and remove flows in sequence.
// The cluster starts with controller + worker-0. WorkerAdd creates worker-1,
// then WorkerRemove deletes worker-1.
func workerLifecycleOnCall(t *testing.T) func([]string, string) mock.Result {
	t.Helper()

	nodesConf := "# Generated by sind\n" +
		"NodeName=worker-0 CPUs=2 RealMemory=2048 State=UNKNOWN\n" +
		"PartitionName=all Nodes=worker-0 Default=YES MaxTime=INFINITE State=UP\n"

	// Track whether worker-1 has been added so remove can include it.
	added := false

	return func(args []string, _ string) mock.Result {
		if len(args) == 0 {
			return mock.Result{}
		}
		joined := strings.Join(args, " ")

		switch {
		case args[0] == "ps":
			if added {
				return mock.Result{Stdout: workerContainers("worker-0", "worker-1")}
			}
			return mock.Result{Stdout: workerContainers("worker-0")}

		case args[0] == "inspect" && args[1] == "sind-dns":
			return mock.Result{Stdout: inspectJSON(t, "sind-dns", "running", map[docker.NetworkName]string{
				"sind-mesh": "10.0.0.2",
			})}

		case args[0] == "inspect" && args[1] == "sind-dev-controller":
			return mock.Result{Stdout: inspectJSONLabels(t, "sind-dev-controller", "running",
				map[docker.NetworkName]string{"sind-dev-net": "10.0.1.1"},
				docker.Labels{"sind.slurm.version": "25.11.0"})}

		case args[0] == "inspect" && strings.HasPrefix(args[1], "sind-dev-worker-"):
			return mock.Result{Stdout: inspectJSON(t, args[1], "running", map[docker.NetworkName]string{
				"sind-dev-net": "10.0.1.3",
			})}

		case args[0] == "exec" && args[1] == "sind-ssh" && len(args) > 2 && args[2] == "cat":
			// ReadFile: SSH pubkey
			return mock.Result{Stdout: "ssh-ed25519 AAAA-test-key\n"}

		case args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "cat":
			// ReadFile: sind-nodes.conf
			return mock.Result{Stdout: nodesConf}

		case args[0] == "exec" && args[1] == "-i" && strings.Contains(joined, "sind-dev-controller"):
			// WriteFile: updated sind-nodes.conf
			return mock.Result{}

		case args[0] == "exec" && args[1] == "sind-dev-controller" && len(args) > 2 && args[2] == "scontrol":
			return mock.Result{}

		case args[0] == "create":
			added = true
			return mock.Result{Stdout: "new-cid\n"}

		case args[0] == "network" && args[1] == "connect":
			return mock.Result{}

		case args[0] == "start":
			return mock.Result{}

		case args[0] == "exec":
			container := args[1]
			if container == "-i" {
				return mock.Result{}
			}
			if len(args) > 2 {
				switch cmd := args[2]; {
				case cmd == "sh" && strings.Contains(joined, "is-system-running"):
					return mock.Result{Stdout: "running\n"}
				case cmd == "bash" && strings.Contains(joined, "/dev/tcp"):
					return mock.Result{Stdout: "SSH-2.0-OpenSSH_9.0\n"}
				case cmd == "mkdir":
					return mock.Result{}
				case cmd == "ssh-keyscan":
					return mock.Result{Stdout: "localhost ssh-ed25519 AAAA-hostkey-" + container + "\n"}
				case cmd == "systemctl" && len(args) > 3 && args[3] == "enable":
					return mock.Result{}
				case cmd == "systemctl" && len(args) > 3 && args[3] == "is-active":
					return mock.Result{Stdout: "active\n"}
				}
			}
			return mock.Result{}

		case args[0] == "cp":
			if len(args) == 3 && args[2] == "-" && strings.Contains(args[1], "sind-dns") {
				return mock.Result{Stdout: emptyCorefileTar()}
			}
			return mock.Result{}

		case args[0] == "kill":
			return mock.Result{}

		case args[0] == "rm":
			return mock.Result{}
		}

		t.Logf("unhandled lifecycle mock call: %v", args)
		return mock.Result{}
	}
}

func TestWorkerAddRemoveLifecycle(t *testing.T) {
	var m mock.Executor
	m.OnCall = workerLifecycleOnCall(t)
	client := docker.NewClient(&m)
	mgr := mesh.NewManager(client, mesh.DefaultRealm)

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()

	// Add a managed worker.
	nodes, err := WorkerAdd(ctx, client, mgr, WorkerAddOptions{
		ClusterName: "dev",
		Count:       1,
		CPUs:        2,
		Memory:      "2g",
		TmpSize:     "1g",
	}, time.Millisecond)

	require.NoError(t, err)
	require.Len(t, nodes, 1)
	assert.Equal(t, "worker-1", nodes[0].Name)
	assert.Equal(t, config.RoleWorker, nodes[0].Role)
	assert.Equal(t, StateRunning, nodes[0].State)

	// Remove the worker.
	err = WorkerRemove(ctx, client, mgr, "dev", []string{"worker-1"})
	require.NoError(t, err)

	// Verify both add and remove operations happened.
	var created, removed bool
	for _, call := range m.Calls {
		args := call.Args
		joined := strings.Join(args, " ")
		if args[0] == "create" && strings.Contains(joined, "sind-dev-worker-1") {
			created = true
		}
		if args[0] == "rm" && strings.Contains(joined, "worker-1") {
			removed = true
		}
	}
	assert.True(t, created, "worker-1 should be created during add")
	assert.True(t, removed, "worker-1 should be removed during remove")
}
